### ISSUE TITLE
Fabric view: Clicking on service API docs icon doesn't work well in Safari

### ISSUE THREAD

**Issue by tilleryd** [DecipherNow/gm-fabric-dashboard#1001]
## Expected Behavior
Clicking on the docs icon should consistently open the API docs.

## Actual Behavior
Clicking on the docs icon doesn't always open the API docs as intended.  I think the hit area is shifting with the animation causing the click event to not be triggered.

## Steps to Reproduce the Problem

  1. Click on any service API doc link.  You may need to try multiple times to see the issue.

## Specifications

  - Version: 0.9.1
  - Platform: macOS Sierra
  - Subsystem: Safari . 10.1

**Comment by karinakeen** [comment]
I read that transitions and animations reset the z-index of footer.  Then footer area is the same clickable area as card layout on hover, as the animation expands the card itself.  Looking for possible vendor prefix as it's working fine in Chrome..
