### ISSUE TITLE
Service view: apply UpTime component to service list items

### ISSUE THREAD

**Issue by tilleryd** [DecipherNow/gm-fabric-dashboard#1003]
At present the up time for list items on the Service view update every 5 seconds on polling intervals but it'd be better if the updates were every second like Service Instance view.  This will help make the app feel more consistent.

**Comment by spmcbride1201** [comment]
Meaning the rightmost column in this screenshot
![image](https://user-images.githubusercontent.com/8700322/33614243-c8c170e8-d9a4-11e7-95c5-555b88889056.png)
