### ISSUE TITLE
Instance view: route sparklines do not always show large spikes that are shown in the large chart

### ISSUE THREAD

**Issue by tilleryd** [DecipherNow/gm-fabric-dashboard#1008]
![screen shot 2017-11-15 at 5 09 34 pm](https://user-images.githubusercontent.com/2581080/32862958-d3819cba-ca27-11e7-9124-cd68200056a6.png)

Looking at the screenshot's `/homehtml` chart, it seems that 0 activity followed by a spike then followed by 0 activity again may be the culprit.  The `/metrics_service_versions_inst_` chart ad a lot of activity with 1 spike which is displayed in it's associated sparkline.  

## Specifications

  - Version: 0.9.1
  - Platform: macOS Sierra 10.12.4
  - Subsystem: Safari 10.1

**Comment by spmcbride1201** [comment]
This looks like my changes to use floats instead of integers might now have affected sparklines.
