### ISSUE TITLE
Threads buttons - All Threads, Active, Idle, Stopped  - are all differently sized

### ISSUE THREAD

**Issue by karinakeen** [DecipherNow/gm-fabric-dashboard#1012]
## Expected Behavior

buttons look uniform and similarly sized 

## Actual Behavior

buttons widths differ based on status text and number of threads for the status.  `All Threads 27` is twice wider than `Idle 8`, and four buttons of varying sizes lined next to each other looks off.

## Steps to Reproduce the Problem

  1. Navigate to JVM Instance Threads View
<img width="1333" alt="screen shot 2017-11-15 at 4 06 01 pm" src="https://user-images.githubusercontent.com/26534838/32863496-b7bc70ca-ca29-11e7-8815-46ce420debd3.png">

## Specifications

  - Version: macOS High Sierra V 10.13
  - Platform: Chrome 61

**Comment by spmcbride1201** [comment]
This is wrapped up in @shanberg's refactor to use his Button component.
