### ISSUE TITLE
FF 57: can tab over instance menu items, but focus isn't visible 

### ISSUE THREAD

**Issue by 7ruth** [DecipherNow/gm-fabric-dashboard#1017]
## Expected Behavior

Focus over the tabs should be visible.

## Actual Behavior

Its not.

## Steps to Reproduce the Problem

  1. In FF 57, navigate to any instance and start tabbing.

## Specifications

  - Version: 0.9.1
  - Platform: fabric

**Comment by karinakeen** [comment]
@7ruth I think this problem has been fixed.  Could you post a screenshot of the instance page you are referring to?

**Comment by 7ruth** [comment]
This is no longer an issue since focus is on links vs the tabs now.
