### ISSUE TITLE
Instance view: HTTP tab: total requests don't align

### ISSUE THREAD

**Issue by tilleryd** [DecipherNow/gm-fabric-dashboard#1020]
## Expected Behavior
The sum of the Response Status Codes should be equivalent to the total HTTP(s) Requests.

## Actual Behavior
<img width="1288" alt="screen shot 2017-11-15 at 8 41 56 pm" src="https://user-images.githubusercontent.com/2581080/32869550-8fbbac96-ca45-11e7-9c5c-f42e39ac4610.png">

In this example the sum of the status codes is 97,239 but the expected value should be 97,241.

## Steps to Reproduce the Problem

  1. Navigate to a service instance view
  1. Click on the HTTP tab
  1. Sum up the total response status codes and observe that they don't match the total HTTP(s) requests.

## Specifications

  - Version: 0.9.1
  - Platform: macOS Sierra 10.12.4
  - Subsystem: Safari 10.1

**Comment by kaitmore** [comment]
Can confirm this bug also exists in Chrome 62 and Safari 11

**Comment by karinakeen** [comment]
Response Status Codes numbers are not dynamic.  They are read off from the `json-moc/jvm/metrics.json` file.  I looked at how metrics are updated when we run mock-sds and it doesn't look like the status codes are updating for the selected instance.

**Comment by karinakeen** [comment]
The numbers seem to match on edge.deciphernow.com

<img width="1338" alt="screen shot 2017-11-28 at 4 59 38 pm" src="https://user-images.githubusercontent.com/26534838/33346394-941b7b00-d45d-11e7-93f9-845157c30583.png">

**Comment by karinakeen** [comment]
@tilleryd The numbers update rather fast on `discovery-service` on edge.deciphernow.com so it may or may not be working when we use real data instead of mock.
<img width="1320" alt="screen shot 2017-11-28 at 5 03 31 pm" src="https://user-images.githubusercontent.com/26534838/33346603-4c477184-d45e-11e7-8983-5c33511fcb6f.png">

**Comment by spmcbride1201** [comment]
Closing this because as @karinakeen pointed out, this discrepancy is in the metrics produced by Twitter Finagle.
