### ISSUE TITLE
Instance view: Go: Routes: sorting by Error % only works once

### ISSUE THREAD

**Issue by tilleryd** [DecipherNow/gm-fabric-dashboard#1021]
## Expected Behavior
Sorting by Error % should work consistently not just once.

## Actual Behavior
Sorting by Error % works once but then subsequent attempts do nothing.

## Steps to Reproduce the Problem

  1. Navigate to a Go service instance
  1. Click on the Routes tab
  1. Sort by Error %
  1. Sort by Error % again
  1. Observe that sorting doesn't take place

## Specifications

  - Version: 0.9.1
  - Platform: macOS Sierra 10.12.4
  - Subsystem: All browsers

**Comment by karinakeen** [comment]
Error % doesn't toggle ascending/descending order.

**Comment by tilleryd** [comment]
I think the work that @kaitmore has been doing in #1023 should resolve this issue. @karinakeen please re-test after #1023 is merged in.
