### ISSUE TITLE
Fabric Main View and JVM/GO List of Instances View - Selecting same sort option should toggle ascending/descending order

### ISSUE THREAD

**Issue by karinakeen** [DecipherNow/gm-fabric-dashboard#1023]
## Expected Behavior

Selecting same sort option[Name, Status] should toggle ascending/descending sort order 

## Actual Behavior

Doesn't change ascending/descending order

## Steps to Reproduce the Problem

For Main Fabric View
  1.  On main fabric view, choose either Card or List view, and click on the same Sort option twice

For JVM/GO service list of instances view
  1.  Navigate to either JVM/GO service, and click on the same Sort option twice 

  
## Supporting Images or Videos
![screen shot 2017-11-16 at 11 28 26 am](https://user-images.githubusercontent.com/26534838/32902828-76df660a-cac1-11e7-8078-5dd70ac61cb7.png)

![screen shot 2017-11-16 at 11 51 15 am](https://user-images.githubusercontent.com/26534838/32904032-7e1e25c0-cac4-11e7-99f6-ef9641e61cfb.png)

## Specifications

  - Version: macOS High Sierra V 10.13
  - Platform: Witnessed in Chrome 62, Safari 11.0, expecting the same behavior in all other browsers
  - Subsystem:

**Comment by kaitmore** [comment]
@spmcbride1201 @tilleryd In Fabric View, do we want the user to be able to toggle asc/desc for Sort By Status? My original impression was that it was designed to always render in the order Down, Warning, Stable

**Comment by kaitmore** [comment]
@spmcbride1201 Deleted any references to forms.scss, fixed Safari regression, and updated snapshots 👍🏼

**Comment by kaitmore** [comment]
@spmcbride1201 I have the as/desc toggle working for sort by name. Should I implement it for sort by status?
