### ISSUE TITLE
App header tab details do not align, margin and capitalization are inconsistent

### ISSUE THREAD

**Issue by karinakeen** [DecipherNow/gm-fabric-dashboard#1035]
## Expected Behavior

Consistent styling

## Actual Behavior

App header tab details texts don't align, margin and capitalization are inconsistent.

## Steps to Reproduce the Problem

  1. Navigate to JVM Instance Dashboard and look at app header tabs
 
## Supporting Images or Videos

- App header tab` HTTP` contents `Received` and `Sent` data should align left or right.
- the left margin for appheader tab details align with tab title, which probably means we should have  minimum right margin.  When tab details are long, the texts cut into right margin, as seen in JVM tab header.

![screen shot 2017-11-16 at 3 28 37 pm](https://user-images.githubusercontent.com/26534838/32914234-db2e9966-cae2-11e7-9a84-46da5ff6f0af.png)

## Specifications

  - Version: problem witnessed in Chrome 61, 62 and expect in all browsers

**Comment by spmcbride1201** [comment]
This should be converted into an epic and decomposed into different issues. This also brings up substantial responsiveness concerns, which will require extensive testing on all supported browsers at different screen sizes.

**Comment by spmcbride1201** [comment]
I'm going to break some of these points out as issues and some as discussion threads. Adding right margin further reduces the content area, which would require text to wrap (which is worse in my opinion)
