### ISSUE TITLE
Slash missing from the User Service service documentation link

### ISSUE THREAD

**Issue by jsweetland** [DecipherNow/gm-fabric-dashboard#1040]
## Expected Behavior
The URL for the User Service service documentation link is https://edge.deciphernow.com/services/user/1.0/home.html.

## Actual Behavior
The URL for the User Service service documentation link is https://edge.deciphernow.comservices/user/1.0/home.html, which is missing the slash between "deciphernow.com" and "services".

## Steps to Reproduce the Problem
  1. Open the GM Fabric Dashboard.
  1. Click the documentation link for the User Service service.
  1. Note that the page does not load because there is a slash missing from the URL as noted above.
  
## Supporting Images or Videos
![image](https://user-images.githubusercontent.com/7924822/32962013-cd476e20-cb98-11e7-9949-7fe86e81d0e7.png)

## Specifications
  - Version: 1.0.0
  - Platform: Opera 48.0 on macOS High Sierra 10.13.1

**Comment by spmcbride1201** [comment]
@jsweetland - Can you please move this issue over to https://github.com/DecipherNow/discovery-service/issues? We're getting this information from the API.
