### ISSUE TITLE
Remove index.scss, mixins.scss, and functions.scss

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#1052]

**Comment by karinakeen** [comment]
blocked by #1045

**Comment by karinakeen** [comment]
@spmcbride1201 We have remaining css files `react-grid-layout.css` and `react-resizable.css` from `React-Grid-Layout`.  Worth try refactoring them into styled-components?

**Comment by spmcbride1201** [comment]
@karinakeen - I think it might be hard to refactor those because we've disabled the ability to let users resize charts. I'm pretty sure most of those styles are used to style the resize behaviors.
