### ISSUE TITLE
Routes Table Wrapping on IE11

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#1063]
## Expected Behavior

Table columns resize and clip to avoid reflows

## Actual Behavior

Last column of the table is always reflowing

## Steps to Reproduce the Problem

  1. Navigate to the Go Routes table in IE11
  2. Check out other tables to see if this is isolated or a common problem
  
## Supporting Images or Videos

![image](https://user-images.githubusercontent.com/8700322/33134790-a654df76-cf6e-11e7-9a64-eadb54a36b00.png)

## Specifications

  - Version: v1.0.0
  - Platform: Windows 7
  - Subsystem: IE 11

**Comment by karinakeen** [comment]
Checked the problem exists in other table views in IE11, JVM > Routes, Go > Routes and Go > Functions

**Comment by karinakeen** [comment]
There seems to be phantom margin created by IE11 browser that is causing the flex column items to overflow.  Manually reducing flex-basis sizes (15% -> 12%) for individual columns should fix the overflow problem.  Maybe we should implement dynamic column sizing that calculates margin ` flex: 1 1 calc(20%-margin size)` after a common GMTable is implemented.
