### ISSUE TITLE
Discuss improvements to the release process

### ISSUE THREAD

**Issue by tilleryd** [DecipherNow/gm-fabric-dashboard#1066]
Current steps (some of which can be automated)
- update package.json version number
- update src/components/AppHeader/components/AppToolBar/index.js with version number
- changelog
  - what's changed
  - version numbers
  - links to build artifacts
- draft new release via GitHub
- build the app
- build Docker image, push to Docker Hub
- formally release draft

Potential Changes to our day to day process:
- Developers should update CHANGELOG.md when they put up a PR.  Then when a release is cut, someone manually cleans up the changelog.

What can we automate?
- change source code to reflect new version (app header, package.json)

**Comment by spmcbride1201** [comment]
Let's move this over to the Teams discussions section and close out this issue.

**Comment by tilleryd** [comment]
Moved discussion to https://github.com/orgs/DecipherNow/teams/grey-matter-fabric-dashboard/discussions/3
