### ISSUE TITLE
SSL certificate errors are preventing Web Workers from loading as expected

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#110]
In the current [private.deciphernow.com](https://private.deciphernow.com/services/) environment, we have to add the site as a security exception to be able to navigate to web apps. While this renders, this environment isn't sufficiently trustable to allow the loading of external scripts for execution as Web Workers, the primary means of achieving multi-threading in an browser. Because of the relatively large amounts of timeseries data that can potentially be cached, filtered, and manipulated in the browser, I consider it pretty critical to get this work moved off the primary UI thread.

What would it take for us to have a trusted HTTPS environment able to do this?
Do you consider it a requirement for me to provide a fallback means to run this work on the UI thread in case of TLS security cert issues  or other trust issues or should the web app explicitly break under those circumstances?

![image](https://user-images.githubusercontent.com/8700322/28272497-aed5643a-6ad9-11e7-8d45-b7143dadad97.png)

```
An SSL certificate error occurred when fetching the script.
service-worker.js Failed to load resource: net::ERR_INSECURE_RESPONSE
registerServiceWorker.js:39 Error during service worker registration: DOMException: Failed to register a ServiceWorker: An SSL certificate error occurred when fetching the script.
(anonymous) @ registerServiceWorker.js:39
```

**Comment by spmcbride1201** [comment]
This is potentially due to the HTTPS self-signed cert / security exception in the private.deciphernow.com environment. All work shifting scraping into a WebWorker should wait to move forward until this is resolved.

**Comment by joshua-rutherford** [comment]
We have no self-signed certificates in the private.deciphernow.com deployment.  They are all signed by a CA, however that CA may not be trusted as it was stood up for this purpose only.

I could use a bit more context to track this down.

1. What is a service worker?
2. What service is it attempting to communicate with?
3. Is the root certificate for our CA trusted by the browser?

**Comment by joshua-rutherford** [comment]
@spmcbride1201, I don't know if the title change was supposed to resolve my first question above, but I'm afraid it only means I have to s/service worker/web worker/.  I can move forward without knowing the answer I think but the second two questions are still valid, I think?

**Comment by spmcbride1201** [comment]
I'm not **quite** that passive aggressive. I changed the title and realized that I'm probably conflating service workers and web workers, which are two somewhat similar yet different primitives that provided by the browser environment. 

A "Web Worker" is best thought of as spinning up a second thread. It does work off the main thread, which prevents the UI from hanging or stuttering. A "service worker" is a type of "Web Worker" that essentially proxies all outbound network calls from the web app and lives beyond when the browser closes to be able to receive pushed data from the server, which allows for more advanced progressive rendering and offline-first techniques, including things like the Push and Notification APIs.

We have a "Service Worker" from the boilerplate starter kit I used to generate the app (but it's not doing much.. other than complaining about HTTPS not being available).

For a lot of the stuff I need to do this week, I can suffice with a normal "Web Worker," which upon further reading, I don't think requires HTTPS.

So IMHO, we're still going to want to get this issue resolved to be able to get things like operating system notifications working (probably pretty useful for this app), but it's not blocking anything immediate.

It's probably worth watching like the first five minutes of [this YouTube video](https://www.youtube.com/watch?v=jVfXiv03y5c) to get the 10k foot view of service workers.

**Comment by spmcbride1201** [comment]
Maybe check [this one out too.](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

**Comment by joshua-rutherford** [comment]
Thanks be to gmail for giving me the youtube clip in the e-mail notification sparing me the rick roll.

**Comment by joshua-rutherford** [comment]
Wow, thorough.  Thank you.

Based on what you've said it seems that the issue might likely be resolved by trusting the CA root certificate from your keychain.  If you trust that CA certificate you will a) not be required to override chrome's self defense mechanisms every time you visit the page, but b) your browser (I'm postulating) will be able to access these things without you present.  Just a guess.

Have you trusted the root certificate?

**Comment by joshua-rutherford** [comment]
Also, I am truly amazed at what is happening in browser land now.  I was driven to things like Silverlight the last time I worked in that area just to get local data stores.  Awesome.

**Comment by spmcbride1201** [comment]
Even thought we pretty much figured out that I had confused myself, I'm going to keep this open until I do a test deploy of my new Web Worker stuff. I removed the Service Worker stuff that I inherited from Create React App, so I think that I shouldn't see any errors about TLS stuff anymore.

**Comment by spmcbride1201** [comment]
Deployment of 0.2.1 confirmed that web workers work as expected. Closing this issue, but this will block us if we later seek to implement service worker functionality.
