### ISSUE TITLE
Only keyboard users should get focus outlines

### ISSUE THREAD

**Issue by shanberg** [DecipherNow/gm-fabric-dashboard#1101]
## Expected Behavior
Clicking items on page should not produce odd blue borders where I don't expect them.

## Actual Behavior
Clicking around in the Services list results in a blue border along the top of the list area.

## Steps to Reproduce the Problem
  1. Open the Service list.
  2. Click the empty background area of a services list area.
  3. Observe blue border (styled blue in Safari. May have other style in other browsers) along the top of the list area.

## Supporting Images or Videos
![screen shot 2017-11-28 at 9 55 43 am](https://user-images.githubusercontent.com/98312/33326207-4f5bc352-d422-11e7-9eb2-5340f8bc6163.png)

## Specifications

  - Version: 1.0.1
  - Platform: macOS
  - Subsystem: Safari 11.1

**Comment by shanberg** [comment]
I like the recommendation here: https://stackoverflow.com/questions/18000090/no-outline-on-mouse-focus-but-still-have-outline-on-keyboard-focus to enable outlines only on keyboard focus, but I'm open to other ideas.

Part of the effort here is to define a better focus outline style overall that fits better with the rest of the theme, but that is a separate issue.

**Comment by 7ruth** [comment]
Places where this happens:

(clicking activates outline)

- Main view area grid container
- Routes, Functions drawers (JVM/GO)
- Explorer view table
- List view
- Service Instances view (table rows and links within)

**Comment by kaitmore** [comment]
Resolved by #1124
