### ISSUE TITLE
IE11: Routes/Functions/Threads tables, need to press tab twice to move

### ISSUE THREAD

**Issue by 7ruth** [DecipherNow/gm-fabric-dashboard#1123]
## Expected Behavior

Need to press one tab to move down a row

## Actual Behavior

Need to press two tabs

## Steps to Reproduce the Problem

  1. Use IE11 to navigate to table and start tabbing
  2. When outline disappears, open IE console and enter ``` document.activeElement ``` 
  3. This will show what element its focusing on, its an svg thats part of sparkline column... I tried putting tabIndex= -1 on it but that didn't help... need another solution
  
## Specifications

  - Version: 1.0.1
  - Platform: fabric

**Comment by karinakeen** [comment]
IE10, IE11, and Edge support focusable, if you don't specify focusable="false", SVG elements are added to the tab order by default in those browsers, with no way of removing them (tabindex is ignored).  Problem is I am not able to set focusable attribute to `svg` returned by SparkLines.   Looking for possible workaround.
