### ISSUE TITLE
Tooltip info need for Latency table headings in Routes

### ISSUE THREAD

**Issue by shanberg** [DecipherNow/gm-fabric-dashboard#1128]
## Expected Behavior
For sake of argument, I don't necessarily know what "Latency 50%" means. I expect to be able to hover the table heading and see a tooltip explaining precisely what it means.

## Actual Behavior
Hovering the table heading shows no additional info

## Specifications

  - Version: 1.0.1
  - Platform: macOS
  - Subsystem: Safari

**Comment by spmcbride1201** [comment]
Good idea! For the record, latency 50% is basically the average latency of the 50% percentile (this approximates the median latency) and latency 99% is the average latency for the slowest 1% of responses. This is the "tail latency," and it's considered by many to be the most important latency metric.

**Comment by chrismholmes** [comment]
This is good and this is good information.  These are important statistics to show on the dashboard as well, especially Avg. latency and Tail latency.
