### ISSUE TITLE
"Requests per minute" setting is mislabled

### ISSUE THREAD

**Issue by shanberg** [DecipherNow/gm-fabric-dashboard#1129]
## Expected Behavior
Moving the slider to fewer requests per minute should reduce the number of requests per minute. Moving the slider to more requests per minute should increase the number of requests per minute.

## Actual Behavior
Moving the slider to the left, to the smaller number, increases the frequency of polling. Moving the slider to the right, to the higher number, reduces the frequency of polling.

## Specifications

  - Version: 1.0.1
  - Platform: macOS
  - Subsystem: Safari

**Comment by spmcbride1201** [comment]
Good catch. I hadn't noticed that label amazingly. The label should be something like "Polling Interval (s)"

**Comment by shanberg** [comment]
Perhaps it could still be clearer than that...

```
Polling Rate

    [12/min]
Fast ----------------- Slow
