### ISSUE TITLE
Summary Bar Cards are varying widths in Edge 14, 15, 16

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#1140]
## Expected Behavior

Cards should be consistent width.

## Actual Behavior

Cards are varied widths.

## Steps to Reproduce the Problem

  1. Open App in Edge
  2. Select Microservice
  3. Select Instance

Related to #1108 
  
## Supporting Images or Videos
![image](https://user-images.githubusercontent.com/8700322/33558729-abb5fa0e-d8d8-11e7-865a-5835c44951f5.png)

## Specifications

  - Version: 1.0.1
  - Platform: Windows 10
  - Subsystem: Edge 16

**Comment by karinakeen** [comment]
TabGraph is stretching out container width in Edge.  Looking for fix

**Comment by karinakeen** [comment]
@spmcbride1201 assigning fixed width to TabGraph is the only approach that worked but we need the width to be dynamic...so I am handing this over to you.
