### ISSUE TITLE
Add Reactopt support to understand unnecessary renders

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#1158]
https://github.com/reactopt/reactopt

**Comment by karinakeen** [comment]
@spmcbride1201 I don't think this works with our app.  Followed install instructions and reactoptcan't load localhost:3000.  There is an open issue asking if the npm module works with webpack and it hasn't been answered yet. 

`npm run reactopt localhost:####`

![screen shot 2017-12-05 at 1 29 37 pm](https://user-images.githubusercontent.com/26534838/33623837-5fb2f9fc-d9c0-11e7-8d27-8530a1f157dd.png)


https://github.com/reactopt/reactopt/issues/73
