### ISSUE TITLE
Sparklines are cut off in table

### ISSUE THREAD

**Issue by kaitmore** [DecipherNow/gm-fabric-dashboard#1200]
## Expected Behavior
You should be able to see the full sparkline graph

## Actual Behavior
Bottom of graph is cut off:
<img width="221" alt="screen shot 2017-12-11 at 3 10 44 pm" src="https://user-images.githubusercontent.com/22768918/33851654-a027be18-de85-11e7-92ea-1b3bb41c9ab7.png">

## Steps to Reproduce the Problem

  1. Navigate to any route or function table in GO/JVM

**Comment by karinakeen** [comment]
This probably has to do with minimum margin set on sparkline container
