### ISSUE TITLE
Warning: react-modal: App element is not defined

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#1222]
## Expected Behavior

No warnings presented in console when clicking on Clear Cache

## Actual Behavior

When opening the settings clear cache confirmation modal, the following warning appears in the console

Warning: react-modal: App element is not defined. Please use `Modal.setAppElement(el)` or set `appElement={el}`. This is needed so screen readers don't see main content when modal is opened. It is not recommended, but you can opt-out by setting `ariaHideApp={false}`.

## Steps to Reproduce the Problem

  1. Start App
  2. Go to Settings
  3. Open Console
  4. Click on Clear Cache
  
## Supporting Images or Videos

![image](https://user-images.githubusercontent.com/8700322/33942862-486093ce-dfe5-11e7-8bbf-d1c48b93fbc5.png)

## Specifications

  - Version: 1.0.2
  - Platform: Mac OS High Sierra
  - Subsystem: Chrome

**Comment by 7ruth** [comment]
@spmcbride1201, #1207 solved this. I just checked master and the warning isn't there, could you please verify?

**Comment by spmcbride1201** [comment]
Roger roger

**Comment by spmcbride1201** [comment]
@7ruth speaks the 7ruth. Issue rescinded.
