### ISSUE TITLE
Implement "No Threads Found" Error component for Threads View

### ISSUE THREAD

**Issue by kaitmore** [DecipherNow/gm-fabric-dashboard#1268]
## Expected Behavior
When no threads are present I would expect an error component similar to Routes View: 
<img width="1440" alt="screen shot 2017-12-20 at 12 20 47 pm" src="https://user-images.githubusercontent.com/22768918/34219768-3b807930-e580-11e7-8778-73d2c558f864.png">

## Actual Behavior
Instead I see an empty table:
<img width="1440" alt="screen shot 2017-12-20 at 12 19 41 pm" src="https://user-images.githubusercontent.com/22768918/34219752-262a8ecc-e580-11e7-91e6-5c1c554b4903.png">

## Steps to Reproduce the Problem

  1. View dashboard without running the fabric server
  2. Navigate to threads view

**Comment by spmcbride1201** [comment]
It seems like there are a few states here:
1. The dashboard fetches from the threads endpoint successfully and there are threads
2. The dashboard fetches from the threads endpoint successfully and there are no threads
3. The dashboard fails to fetch from the threads endpoint

In the case of the last situation, we currently also display an error popup as below:
![image](https://user-images.githubusercontent.com/8700322/34488038-d5fe288a-efa4-11e7-9a8d-1470eddc0369.png)

I feel like it's a bit misleading if the threads endpoint request fails and we display the message "No Threads Found". I'd prefer to have a distinct error state like "Failed to fetch Threads" for state 3. I think your proposal would be good for state 2.
