### ISSUE TITLE
JVM Routes table sort by latency

### ISSUE THREAD

**Issue by kaitmore** [DecipherNow/gm-fabric-dashboard#1272]
## Expected Behavior
I would think we should be able to sort by latency like in the Go routes table:
<img width="1439" alt="screen shot 2017-12-21 at 9 07 30 am" src="https://user-images.githubusercontent.com/22768918/34259036-a284308c-e62e-11e7-8c22-585e0c90e6c1.png">

## Actual Behavior
<img width="1440" alt="screen shot 2017-12-21 at 9 02 52 am" src="https://user-images.githubusercontent.com/22768918/34258840-d4a82970-e62d-11e7-9e40-0a0d7f7da96f.png">

**Comment by spmcbride1201** [comment]
Good catch! Let's do it!
