### ISSUE TITLE
Refactor AppHeader/scenes

### ISSUE THREAD

**Issue by kaitmore** [DecipherNow/gm-fabric-dashboard#1282]
AppHeader/scenes/NoSDS/Header.js seems to be an unnecessary intermediate component that just renders InstanceHeaderContent  

Perhaps this directory could be refactored like:
```
| AppHeader/
|  --- scenes/
|    --- FabricHeaderContent/
|    --- ServiceHeaderContent/
|    --- InstanceHeaderContent/
```

**Comment by spmcbride1201** [comment]
Yep, it has no functional purpose as you say. I think the intention here was just to provide a folder hierarchy that makes the different states a bit easier to understand. I think we can sacrifice the UseSDS / NoSDS scenes to flatten as your propose.
