### ISSUE TITLE
Investigate 'with-url-state' as a way to simplify url query param logic

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#1355]
## Proposed Changes
* Currently, we use pretty complex custom logic to manage our URL state. I propose moving to https://github.com/Dean177/with-url-state or a similar library to simplify our approach

I suspect that much of our complexity is in fact due to the fact that we pass logic as props directly and then bolt-on handling URL params on tops, which causes us to have to deconflict these multiple avenues for state and determine when things take priority. 

It might also be naive of me to suggest this due to the way that we update some queries as the user types in a text field rather than via a full form submission. This might cause additional complexities that require additional planning.

**Comment by kaitmore** [comment]
From the demos, it looks like it doesn't preserve url state on refresh. Looking into other options.
