### ISSUE TITLE
CircleCI Builds seem to run npm install excessively

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#1378]
## Expected Behavior

When the dependency cache is valid, `npm install` is skipped

## Actual Behavior

After the dependency cache is restored, `npm install` seems to always run. This makes our build process about ~20s longer than needed

**Comment by kaitmore** [comment]
@spmcbride1201 Are you still seeing this issue or did we decide that it's behaving normally?

**Comment by spmcbride1201** [comment]
We decided that it's behaving normally!
