### ISSUE TITLE
Persistent Parenthetical Problem

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#1437]
## Actual Behavior

When a microservice has a parenthesis in the name, the instance dashboard renders an error condition when an instance is selected.

## Steps to Reproduce the Problem

  1.
  1.
  1.
  
## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by kaitmore** [comment]
`( ) * : ?` are all reserved characters in react-router. So this leads us back to the same issue David was having with spaces: https://github.com/DecipherNow/gm-fabric-dashboard/pull/861

What's currently happening is parentheses are being treated as optional url params. If we percent encode the parentheses, the history api will automatically decode it before pushing it to the url bar, and it won't match on the route.
