### ISSUE TITLE
Implement SVGs for the various precanned icons

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#144]
Currently, this project is using UIKit v3 beta for a variety of purposes, including providing a rudimentary icon library. This library is no longer sufficient for our purposes and should be replaced with custom SVGs designed by @shanberg, which are currently located in `/src/images/icons/*.svg`

The goal of this project is to be able to treat our SVG icons as React components using the techniques described by https://css-tricks.com/creating-svg-icon-system-react/

Steps:
1. Refactor each of these SVGs into stateless functional React components
2. Enhance the React components to accept props for size and color
3. Enhance the React components with ARIA attributes as detailed in the above article and follow-on comments.
4. Render each of these icons in Storybook, demonstrating the possible uses of props.

**Comment by shanberg** [comment]
https://github.com/DecipherNow/gm-fabric-dashboard/tree/add-custom-icons This branch has new SVGs.

**Comment by spmcbride1201** [comment]
Moving to 0.4.0

**Comment by spmcbride1201** [comment]
@shanberg - Did this stuff get merged in? Or did it get accidentally deleted?

**Comment by shanberg** [comment]
I've replaced the missing branch.

**Comment by spmcbride1201** [comment]
This is actually more than just adding icons. It's creating infrastructure that can read an arbitrary string from the JSON files defining a dashboard and then modifying the renderChart logic to show the icon. Currently this functions based on string interpolation injecting a UIKit icon classname, but this won't work for our custom icons.

**Comment by spmcbride1201** [comment]
@karinakeen & @7ruth - I want you two to pair program on this one.
