### ISSUE TITLE
Graph labels have some confusing labels

### ISSUE THREAD

**Issue by justincely** [DecipherNow/gm-fabric-dashboard#1478]
## Actual Behavior
 The sub-panes in the service instance views have some confusing labels.  Initially I thought it would be Kb, Mb, Gb, but it seems to be 1000, Million, Billion (of bytes presumably?)

A label specifying/explaining the units, or perhaps changing to Kb, Mb, Gb would help clarify.

## Steps to Reproduce the Problem

  1.
  1.
  1.
  
## Supporting Images or Videos

<img width="1339" alt="screen shot 2018-02-06 at 10 58 50 am" src="https://user-images.githubusercontent.com/2422189/35869376-e3f91744-0b2c-11e8-8d39-c2b3d8f2f130.png">

## Specifications
  - Version: 1.0.4
  - Platform: Chrome
  - Subsystem:

**Comment by spmcbride1201** [comment]
Example with labels:
![image](https://user-images.githubusercontent.com/8700322/35884008-3b340e9a-0b57-11e8-83cb-7d1221fa99e9.png)

**Comment by spmcbride1201** [comment]
Another example:
![image](https://user-images.githubusercontent.com/8700322/35884099-7ac64f0a-0b57-11e8-9ec7-2dd832aa4d58.png)
