### ISSUE TITLE
Configure CircleCI to use EST when running our unit tests to prevent timezone issues from breakout our snapshots that use shallow()

### ISSUE THREAD

**Issue by kaitmore** [DecipherNow/gm-fabric-dashboard#1483]
JVMHeaderContent, GoHeaderContent, and Summary views are all using shallow instead of render because of issues with using Date.now in the Uptime component.

When doing a full render, CI fails because dates/times are based on the timezone of the CircleCI server https://medium.com/front-end-hacking/jest-snapshot-testing-with-dates-and-times-f3badb8f1d87

This solution uses `moment`, which is a big library and would require refactoring the Uptime component just so our snapshots work. There is probably a better solution out there like setting the timezone in our circleci config.

**Comment by spmcbride1201** [comment]
I think we'll likely eventually end up bringing in moment or date-fns as our app grows, but setting the timezone in CircleCI seems like a good immediate fix. I recall there being an explicit API to do this in CircleCI 1.0, but it [looks like 2.0 requires us to do things a bit more manually.](https://discuss.circleci.com/t/set-time-zone-in-ci2-0/16494). I'm going to rename this issue to reflect the assumption that setting a consistent timezone will fix the issue.
