### ISSUE TITLE
Implement Codesplitting

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#192]
This should produce the following:
- [x] Main bundle
- [x] Vendor dep bundle
- [x] Per route bundles
- [x] Per web worker bundles NOTE: web worker code was migrated back into the main bundle

**Comment by spmcbride1201** [comment]
Blocked by #401

**Comment by tilleryd** [comment]
Plan:
- use react-loadable https://github.com/thejameskyle/react-loadable to handle the lifecycle of loading async components
- use `ErrorBoundary` component to display any failed async loading of bundles
- start at the Route level
- investigate if other components can be code split
