### ISSUE TITLE
Architecture Discusion: Use of Web Workers to enable modularity and allow potential server-side reuse

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#194]
I was just talking with @tilleryd about how to refactor and modularize the front-end code using Web Workers.

The idea is that most of the state, helper functions, and interfaces (AJAX, WebSockers, gRPC) for a particular dashboard "adapter" gets broken out into a WebWorker. 

This would mean we would have a web worker adapter for the legacy `gm-fabric-jvm` / Amsterdam stuff and a different web worker adapter for the new Envoy/Graphite/Go stuff.

The core UI layer would be made as stateless as possible and have configuration settings that help determine which of the web workers get loaded.

Because Web Workers use a bidirectional message passing interface with the main UI thread, this opens up the possibility of deploying the web worker logic as a server-side Node.js microservice adjacent to Graphite that can cache and proxy the Graphite render APIs and push changes out via WebSockets.

**Comment by joshua-rutherford** [comment]
I think we'll be pushed down the route of having something sit between you and Graphite anyway (as per @jdholmes1978 assertions) so I don't have an issue with a microservice running server side for you, however I'd need a plan on how a Node.js microservice would play with the rest of our requirements for security.
