### ISSUE TITLE
Integrate CircleCI

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#2]
We need to get CircleCI plugged into our pipeline. I'd like each PR to trigger our tests and display the results in the context of the PR.

**Comment by spmcbride1201** [comment]
@tilleryd I created a personal CircleCI account, but I figure we want to look this into an organizational account, right?

**Comment by spmcbride1201** [comment]
Just noticed on my PR that it actually **is** doing what I want, I guess this issue really is if we want to shift this from my personal account and if we do, making the changes as appropriate.

**Comment by chrismholmes** [comment]
@anxiousmodernman can assist with this Sean.

**Comment by anxiousmodernman** [comment]
@spmcbride1201 Does the "[Add the project](https://circleci.com/add-projects)" include the DecipherNow GitHub org? This repository should be under that list. If it's not, ping me on Slack.

Some getting started docs for Circle are [here](https://github.com/DecipherNow/infrastructure/blob/master/docs/CIRCLE_CI.md). It's cool that you're setting CI up early. That makes it way easier in the long run. I've done a few builds, so set some time up with me if you need help.

**Comment by spmcbride1201** [comment]
Looking at it a bit more closely, I guess there was more magic to this setup that I realized, as it appears that everything is working. I'll close once I can confirm that @tilleryd is able to get to project settings.

**Comment by spmcbride1201** [comment]
Just validated that @shanberg was able to view the project in CircleCI, so closing now.
