### ISSUE TITLE
Add commas to large numbers

### ISSUE THREAD

**Issue by shanberg** [DecipherNow/gm-fabric-dashboard#201]

**Comment by shanberg** [comment]
@spmcbride1201 what do you think is our path here? Lots of components are outputting numbers.

**Comment by spmcbride1201** [comment]
I think the solution is to use locale strings and create settings (and later a settings component to control the locale). This will allow us to show the number in the appropriate format for the various countries.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString

**Comment by spmcbride1201** [comment]
Moving to 0.4.0
