### ISSUE TITLE
Allow pinning items to Summary

### ISSUE THREAD

**Issue by shanberg** [DecipherNow/gm-fabric-dashboard#274]
Allow graphs to be added to (and removed from) Summary page via some user action.

- [ ] Capability to add graph item to Summary page
- [ ] Capability to remove individual items from Summary page

**Comment by spmcbride1201** [comment]
@shanberg - I get the sense that our customization story has changed for the summary page. E.g. the user may not be able to customize the dashboards that we provide out-of-box, but they're able to create/modify/delete additional dashboards beyond what we provide. Should we close this?

**Comment by shanberg** [comment]
Yep, I think that's accurate. Closing.
