### ISSUE TITLE
Choose default metrics for Sidebar on first-run UX

### ISSUE THREAD

**Issue by shanberg** [DecipherNow/gm-fabric-dashboard#275]
What (if any) metrics should be displayed by default in the collapsible cards in the Sidebar?

As of 0.3.0, we show [this](https://user-images.githubusercontent.com/98312/29215663-db0ff1c4-7e79-11e7-970e-39e2925539b0.png). I'm not happy with the graphs here, which is completely my fault, and I think there are a lot of different ways we can should be present valuable data. Latest values + Sparklines, Bar charts, etc.

What I'd like to determine here is what metrics should we present to a completely new user, for each of the views, e.g.,
- Routes: If > 1, Number of routes with errors over 40%, + Sparkline
- Threads: Line or area chart comparing Active/Idle/Stopped proportions
- HTTP: Value + Sparkline of Connections, Line or area chart comparing Response types

If there's no single data stream, how can we summarize and roll up many streams into a minified view?

**Comment by chrismholmes** [comment]
This is low priority...higher priority to introduce some color and not have 50 shades of gray.

**Comment by spmcbride1201** [comment]
@shanberg - Can you please close this issue and open new issues for enhancements that you want to see to the primary nav cards? I think the gist is that you think that there might be value in other types of charts other than our current sparklines.

**Comment by shanberg** [comment]
OBE
