### ISSUE TITLE
Implement "Services" and "Instances" Components and expand navigation to an entire Fabric of microservices

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#290]
The dashboard currently only monitors a single instance of a microservice using static configs stored in `meta` tags in their respective `index.html` files.

Having a Fabric-wide view of microservices relies on the presence of the`gm-services-gateway` as a landing page that links to the separate dashboards. The landing page is essentially a static website that has microservice information injected by ZooKeeper/NGINX via Mustache tags.

We intend to enhance `gm-fabric-dashboard` to allow a single instance to monitor an entire microservice fabric.

To make this possible, the following UI changes must occur:
- The SummaryBar component must behave differently based on if it's showing the entire Fabric, a microservice composed of a cluster of instances, or a single instance
- Routing must add parameters for microservices and instances like `/:serviceName/:instanceID/threads` to support the ability to render different microservices
- New components must be created to show something in the main view area. Absent a TSDB, the mocks for dashboards based on metrics rollup across a cluster of instances is not possible, but intermediate content should be generated.

**Comment by spmcbride1201** [comment]
Most of this work is completed in the `93-config-scrape-point` branch, but merging this into `development` is effectively blocked by #291 as the UI component require service discovery type metrics across the Fabric.

**Comment by tilleryd** [comment]
A lot of this is captured in new Epics #393 #395 #396 #397 and much of this work is complete.
