### ISSUE TITLE
[Question] What is responsible for determining the metrics runtime?

### ISSUE THREAD

**Issue by tilleryd** [DecipherNow/gm-fabric-dashboard#308]
Ideally the service would report out its type of runtime - JVM, Go, etc.  This will alleviate the need for the dashboard logic to parse metrics JSON for a particular key to determine the runtime; which is a bit dirty and presumptuous.

**Comment by tilleryd** [comment]
@joshua-rutherford

**Comment by joshua-rutherford** [comment]
I assume this is a requirement in "Phase 1" as discussed with Chris yesterday, right?  If so, then ZooKeeper will not contain this information.  That means modifying quite a bit in what services currently do. However, it would be possible to insert this functionality into a service that sits between you and ZooKeeper and provides additional configuration information on deployed services.

**Comment by spmcbride1201** [comment]
This will be resolved by @joshua-rutherford JVM-based BSDS service.
