### ISSUE TITLE
Error when clicking on Finagle nav item

### ISSUE THREAD

**Issue by tilleryd** [DecipherNow/gm-fabric-dashboard#312]
<img width="1920" alt="screen shot 2017-08-18 at 1 27 50 pm" src="https://user-images.githubusercontent.com/2581080/29470120-20c0ad36-8419-11e7-8394-d39fdcf6c011.png">

**Comment by spmcbride1201** [comment]
Issue was due to cache. Cache busting on roadmap as high priority issue.
