### ISSUE TITLE
Implement Service Discovery Service

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#319]
Implement the API required to enable the dashboard to pull instance-level metrics from the GM-Fabric-JVM `admin/metrics.json` and `admin/threads` endpoints.

This should follow the API pattern established by #318

**Comment by joshua-rutherford** [comment]
@spmcbride1201, I think we can call this closed, right?

**Comment by spmcbride1201** [comment]
http://gph.is/1JdU9Qw
