### ISSUE TITLE
Implement ability to view thread information and stacks

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#32]
This should be functionally similar to the Twitter Server treads view:
![image](https://cloud.githubusercontent.com/assets/8700322/24709354/9e315d7a-19e7-11e7-9f3c-d4fd5f96a520.png)

This information does not seem to come from `metrics.json'.

**Comment by jdholmes1978** [comment]
@spmcbride1201 I think the best corse of action is to outline the calls being made to power this UI/UX view or other views that are not powered by the metrics.json.  We may have to extend the service framework to have an API to use.

**Comment by spmcbride1201** [comment]
After going back through Twitter Server's source and documentation, it turns out that no backend changes are actually needed. I'm going to create a new feature branch for this functionality momentarily.
