### ISSUE TITLE
Dockerize the Service Discovery Service

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#334]

**Comment by spmcbride1201** [comment]
@justincely - Since @joshua-rutherford seems to be moving along pretty well with the actual service, I suggest we modify the scope of this task to working with him to integrate the actual service into your docker-compose. Thoughts?

**Comment by tilleryd** [comment]
@spmcbride1201 That makes sense.  Dockerizing the mock SDS doesn't really buy is much right now.

**Comment by justincely** [comment]
Sorry @spmcbride1201 off in terraform land today. Sounds good to me!
