### ISSUE TITLE
Implement route quality data viz element

### ISSUE THREAD

**Issue by shanberg** [DecipherNow/gm-fabric-dashboard#361]
Routes data viz component was never completed when it was initially pushed. What remains is to connect the length of the colored bar to to the relative volume of traffic across a route.

**Comment by spmcbride1201** [comment]
Note that this UI element is only present for JVM microservices. It was not added to the equivalent Go dashboard.

**Comment by karinakeen** [comment]
@spmcbride1201 how do you want to calculate the relative volume of traffic?

**Comment by karinakeen** [comment]
@shanberg I need more feedback on the issue.

**Comment by shanberg** [comment]
Percentages should be relative to the other routes in the list.

If Route A has 1000 requests per second, Route B has 500 requests per second, and Route C has 10 requests per second, Route A's bar is at 100%, Route B's bar is at 50%, and Route C's bar is at 1%.

The maximum value of all the bars should be the value of the route with the highest volume.

Let me know if that's still ambiguous, or if somebody has a better idea for how to represent traffic.

**Comment by karinakeen** [comment]
![screen shot 2017-10-25 at 5 23 03 pm](https://user-images.githubusercontent.com/26534838/32024395-58b526c4-b9aa-11e7-93c0-89d6e788b5ea.png)
