### ISSUE TITLE
Refactor SCSS used by Services Table

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#368]
Currently the `.routes-table-` prefixed styles are used in:
- Fabric Table
- Go Functions Table
- Go Routes Table
- JVM Routes Table

There is also a JVM Thread Table that might use distinct styles, but it very similar.

Once common styled-components are implemented across these tables, create an issue to identify the possibility of creating a common GMTable molecule that is sufficiently extensible to cover each of these use cases.

**Comment by karinakeen** [comment]
blocked by #533
