### ISSUE TITLE
Implement "Groups" Support

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#372]
This likely is no longer a separate endpoint, but just a string attribute on a service object. Nevertheless, we need utility functions for typical sorting actions. We may also need to delete the groups object in `Fabric` in Redux, as this likely is no longer needed.

**Comment by tilleryd** [comment]
Correct, this will be a new attribute per service returned from the SDS.

**Comment by joshua-rutherford** [comment]
Just to be clear, we always planned on returning a group field in the service object.  The new field is the 'owner' field.  That is, every service from the Discover Service `/services` endpoint will have a `group` and `owner` field that will be some user defined string. 

Sean, we are currently exposing a `/groups` endpoint in the discovery service that returns a list of the groups.  Are you suggesting that:

a) You no longer need that endpoint and will not need an `/owner` endpoint to complement?
b) You would like server side sorting or filtering of services based on group and or owner?

Obviously a) is easy simple but b) does require some implementation (though trivial).

**Comment by joshua-rutherford** [comment]
Actually, I think we said they would be `owner` and `category`.  With the two combining in the grouping functionality.

**Comment by tilleryd** [comment]
OBE by https://github.com/DecipherNow/gm-fabric-dashboard/issues/408
