### ISSUE TITLE
Services Gateway

### ISSUE THREAD

**Issue by tilleryd** [DecipherNow/gm-fabric-dashboard#393]
The top level view displaying all services in the Fabric.

![image.png](https://images.zenhubusercontent.com/59bab3dab0222d5de477c14b/221e00b6-656a-454c-9640-fae14ca3a52f)

**Comment by spmcbride1201** [comment]
Closing this epic, as the Phase 0 LOE has been completed and we've already rolled forward with Phase 1 work.
