### ISSUE TITLE
Services Gateway sub navigation

### ISSUE THREAD

**Issue by tilleryd** [DecipherNow/gm-fabric-dashboard#394]
- Search Input
  - keyword search
  - client side filtering only
  - when updating the URL we need to debounce the keystrokes to minimize history updates
- List type button group
    - options: Cards, Table
- Grouping dropdown
  - options: None, Owner (default)
- Sorting dropdown
  - options: Name (default), Last Updated, Status

Functional requirements:
- Each component shall update the URL.
- JumpState shall react to URL changes and update the Redux state with the currently active option.
- When navigating to the view from a direct URL the view should display control active state accordingly.
- Tabbing through the controls should work as expected to support a11y.

**Comment by joshua-rutherford** [comment]
@tilleryd, on `Grouping`, the options are actually `None`, `Owner` and `Category`

**Comment by tilleryd** [comment]
Closed in favor of https://github.com/DecipherNow/gm-fabric-dashboard/issues/395.
