### ISSUE TITLE
Create a "tips" component that explains how to navigate the card and list views.

### ISSUE THREAD

**Issue by tilleryd** [DecipherNow/gm-fabric-dashboard#403]

**Comment by spmcbride1201** [comment]
This is blocked by actually figuring the navigation out in #518 and #519.

Additionally, with local storage disabled, there isn't a good way to show this only on the initial load. I fear that this would end up being an annoyance for users.

**Comment by tilleryd** [comment]
After giving this some more thought... the card and list views are intuitive to navigate and a tips component would be overkill at this point.
