### ISSUE TITLE
Implement a first time login Welcome notification with "tips" on how to navigate the card and list views.

### ISSUE THREAD

**Issue by tilleryd** [DecipherNow/gm-fabric-dashboard#404]

**Comment by tilleryd** [comment]
This work should come after #403.

**Comment by spmcbride1201** [comment]
This is blocked by actually figuring the navigation out in #518 and #519.

Additionally, with local storage disabled, there isn't a good way to show this only on the initial load. I fear that this would end up being an annoyance for users.

**Comment by tilleryd** [comment]
After giving this some additional thought I realized that navigating the views is pretty intuitive and having a tips component is not needed.
