### ISSUE TITLE
Update Go Dashboards to reflect API changes about memory.

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#431]
```json
	"system/memory/available": 5954699264,
	"system/memory/used": 11225169920,
	"system/memory/used_percent": 65.339088,
	"process/memory/used": 4427776,
```

API changes at https://github.com/DecipherNow/gm-fabric-go/pull/212#pullrequestreview-66582394

**Comment by spmcbride1201** [comment]
@joshua-rutherford, @tilleryd, @dougfort - Are these API changes targeted for our initial release?

**Comment by spmcbride1201** [comment]
@joshua-rutherford - Bumping this to next sprint because we still don't know if/when this might get merged in.

**Comment by joshua-rutherford** [comment]
They've been merged in.  @dougfort and @alecholmez, you two tell me how long and how much effort to update all of the go services?

**Comment by dougfort** [comment]
There's no change to the API, only the text of some JSON keys in the output. Just rebuilding with the latest gm-fabric-go master should suffice.

**Comment by joshua-rutherford** [comment]
So we can have that done in a week.  That would fall on @alecholmez.  @alecholmez, what say you?

**Comment by alecholmez** [comment]
I can do it by the end of tonight

**Comment by spmcbride1201** [comment]
Thanks for the clarification all!
