### ISSUE TITLE
Alignment issues in IE11

### ISSUE THREAD

**Issue by karinakeen** [DecipherNow/gm-fabric-dashboard#456]
IE11

![screen shot 2017-10-05 at 11 48 09 am](https://user-images.githubusercontent.com/26534838/31236842-3c654e5a-a9c3-11e7-8e93-db61e29e0018.png)

Chrome
<img width="1414" alt="screen shot 2017-10-05 at 11 47 53 am" src="https://user-images.githubusercontent.com/26534838/31236830-37aa775a-a9c3-11e7-9cf3-4d17f399179b.png">

**Comment by spmcbride1201** [comment]
@karinakeen - What specifically is misaligned in these screenshots?

**Comment by karinakeen** [comment]
This was an epic-type issue.  Closing as specific issues have been addressed and noted.
