### ISSUE TITLE
Alignment issue in IE11: Sidebar triangledown icons 

### ISSUE THREAD

**Issue by karinakeen** [DecipherNow/gm-fabric-dashboard#457]
Alignment issue in IE11
Sidebar triangledown icons 

IE11
![screen shot 2017-10-05 at 11 50 28 am](https://user-images.githubusercontent.com/26534838/31236962-93a4b5b6-a9c3-11e7-97f4-a09420c44f11.png)

Chrome
<img width="124" alt="screen shot 2017-10-05 at 11 50 15 am" src="https://user-images.githubusercontent.com/26534838/31236959-8fd1a052-a9c3-11e7-9718-005fd9d9d039.png">

**Comment by spmcbride1201** [comment]
This looks like it has to do with scrollbar stuff to me.
