### ISSUE TITLE
Alignment issue in IE11: Magnifier Icon in SearchInput - FabricTableToolbar

### ISSUE THREAD

**Issue by karinakeen** [DecipherNow/gm-fabric-dashboard#463]
Alignment issue in IE11: 
Magnifier Icon in SearchInput - FabricTableToolbar

Magnifier icon is not centered
IE11
![screen shot 2017-10-05 at 12 15 58 pm](https://user-images.githubusercontent.com/26534838/31238223-522f493a-a9c7-11e7-81e7-51a24062b83f.png)

Chrome
<img width="235" alt="screen shot 2017-10-05 at 12 15 44 pm" src="https://user-images.githubusercontent.com/26534838/31238231-5824bdd4-a9c7-11e7-82c7-12b4f5cc84e5.png">

**Comment by spmcbride1201** [comment]
I consider this a super super low priority.
