### ISSUE TITLE
IE11: Clicking on sidebar items in dashboard opens content in a new window

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#475]
@karinakeen saw different behavior in her VM, but I witnessed this in mine. We'll have to investigate further to determine the cause.

**Comment by karinakeen** [comment]
not seeing this behavior.  clicking on 'Grey Matter' at the end of sidebar opens a new window, but other sidebar items(Summary, Routes, Functions,Go) do not open a new window.  possibly related to #475

**Comment by spmcbride1201** [comment]
Ok, closing. We'll reopen if this appears again.

**Comment by spmcbride1201** [comment]
Closing issue as we were unable to reproduce. Will re-open if this re-appears in the future.
