### ISSUE TITLE
Dashboard view alignment issue: Routes (chrome)

### ISSUE THREAD

**Issue by karinakeen** [DecipherNow/gm-fabric-dashboard#476]
Dashboard-Routes
Route paths next to GET and POST buttons should align left

Chrome
![screen shot 2017-10-05 at 2 46 06 pm](https://user-images.githubusercontent.com/26534838/31246664-1694d916-a9dc-11e7-9665-4845dffb0c31.png)

IE
![screen shot 2017-10-05 at 2 47 57 pm](https://user-images.githubusercontent.com/26534838/31246695-36a294fa-a9dc-11e7-9f1f-905a65a634c3.png)

**Comment by spmcbride1201** [comment]
This task is basically to break the labels and the path out into different flex children. This should probably be done in conjunction with adding a new Verb title to the header.

**Comment by spmcbride1201** [comment]
I'm unassigning this issue and shifting it to the backlog to focus on higher priority tasks.
