### ISSUE TITLE
Dashboard view alignment issue: sidebar services under heading (chrome and IE)

### ISSUE THREAD

**Issue by karinakeen** [DecipherNow/gm-fabric-dashboard#477]
Dashboard alignment issue: 

sidebar services under heading 

![screen shot 2017-10-05 at 2 48 50 pm](https://user-images.githubusercontent.com/26534838/31246843-b8d6f9ca-a9dc-11e7-8289-88e789542e2b.png)

**Comment by spmcbride1201** [comment]
I'm not understanding this one. Can you clarify this @karinakeen ?
