### ISSUE TITLE
Dashboard IE11 view alignment issue: Explorer -Search bar sits on top of scroll arrow

### ISSUE THREAD

**Issue by karinakeen** [DecipherNow/gm-fabric-dashboard#483]
Resize the search box to not shield the scroll arrow?

![screen shot 2017-10-05 at 3 02 22 pm](https://user-images.githubusercontent.com/26534838/31247396-72a0aabc-a9de-11e7-8813-947c8c22a772.png)

**Comment by spmcbride1201** [comment]
I believe this is the same in Chrome, but it's just less noticeable with the custom sidebar.

**Comment by spmcbride1201** [comment]
I suspect this might end up being pretty complicated layout-wise, as the search index is currently on a different z-index. It might be acceptable "as-is" is the scrollbar is made thinner. Another possible approach is to make the search box a little narrower to not overlap.

**Comment by spmcbride1201** [comment]
I'm un-assigning this issue and shifting it to the backlog to focus on higher priority tasks.

**Comment by spmcbride1201** [comment]
This is fixed.
