### ISSUE TITLE
Implement ability to navigate to service view

### ISSUE THREAD

**Issue by tilleryd** [DecipherNow/gm-fabric-dashboard#530]
Clicking on list items, cards, and sidebar items should navigate to a URL in the following format:

```
https://edge.deciphernow.com/#/Discovery Service 1.0/ 
```

**Comment by spmcbride1201** [comment]
Blocked by #534

**Comment by spmcbride1201** [comment]
Effectively completed by #571. I'm going to open a different issue around combining the service name and version together in the route to reflect the smaller scope.
