### ISSUE TITLE
Service View

### ISSUE THREAD

**Issue by tilleryd** [DecipherNow/gm-fabric-dashboard#533]
Mock is currently pending...

**Comment by spmcbride1201** [comment]
Blocked pending completion of design mocks.

**Comment by spmcbride1201** [comment]
Blocked by #534 and the completion of the design mock

**Comment by spmcbride1201** [comment]
@shanberg - Can you put the phase 1 service dashboard mock here? There's some implementation work that we need to wrap up still.
