### ISSUE TITLE
Responsively resize cards based on viewport width

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#536]
The cards currently have an absolute width. This means that there can be substantial white space on the right side of the cards.
![image](https://user-images.githubusercontent.com/8700322/31444330-f65a88e8-ae69-11e7-8aa3-c88e781a3e7c.png)

Depending on viewport width, we should be able to resize individual cards appropriately to fill each row. The approach should be satisfied by adding `flex-grow` to the cards.

https://codepen.io/spmcbride1201/pen/PJaRXj

**Comment by kaitmore** [comment]
@spmcbride1201 
After discussing layout options it was concluded that this issue should be tabled until it is decided whether or not to implement css grid.
