### ISSUE TITLE
Sidebar dropdown color in Polling Settings

### ISSUE THREAD

**Issue by kaitmore** [DecipherNow/gm-fabric-dashboard#577]
The color of the dropdown menu in polling settings is too dark: 

![screen shot 2017-10-17 at 11 43 33 am](https://user-images.githubusercontent.com/22768918/31674961-4cea49b6-b331-11e7-9d97-00bc307f072b.png)

**Comment by spmcbride1201** [comment]
This issue is not going to be fixed due to the impending implementation of new app navigation components.
