### ISSUE TITLE
Escape Spaces in URL

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#582]
Currently, the URL includes parameters that have actual spaces, such as the following:
```
https://edge.deciphernow.com/#/Discovery Service/1.0/1ea349346c473b5c50ef9d8899d73229/route
```
When URLs like this are pasted into slack and other chat clients that dynamically link the URL, they interpret the space as terminating the URL. We should use encodeURI() on all parameters to fix this.

**Comment by spmcbride1201** [comment]
@karinakeen - Let me know if you want me to take this on. Not sure where your frustration level is at with this.

**Comment by karinakeen** [comment]
@spmcbride1201 please take the issue.

**Comment by spmcbride1201** [comment]
lol. @tilleryd please take the issue.

**Comment by tilleryd** [comment]
@spmcbride1201 We can safely ignore the service version number and service instance ids from escaping.  The explorer view's routes are already escaped.  So I think it's safe to assume all I need to do is escape the service names.
