### ISSUE TITLE
Confirm that keypress events target both spacebar and return key

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#587]
Task is to go through the app and confirm that keyboard controls are implemented consistently.

Thought: are enter and return different keys? If so, maybe both of them and space.

Thought: React-select only activates on an up or down arrow. It probably should toggle open selecting the currently selected option on space/enter/return.

**Comment by karinakeen** [comment]
return key doesn't work on firing individual service from fabric - table view - service

<img width="819" alt="screen shot 2017-10-23 at 10 42 59 am" src="https://user-images.githubusercontent.com/26534838/31895443-30478b0e-b7df-11e7-9538-adcf1502d692.png">


instances selectable but not highlighted on  fabric -table view - service - instances

<img width="1014" alt="screen shot 2017-10-23 at 10 43 14 am" src="https://user-images.githubusercontent.com/26534838/31895452-358c000e-b7df-11e7-9ea4-6db9926dd6d9.png">

**Comment by karinakeen** [comment]
tested again and created #729
