### ISSUE TITLE
Bring greater consistency to the Routes Components for JVM and Go microservices

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#598]
JVM:
![image](https://user-images.githubusercontent.com/8700322/31726456-0b264da8-b3f5-11e7-97f7-76177a751f57.png)

Go:
![image](https://user-images.githubusercontent.com/8700322/31726503-2783c908-b3f5-11e7-9e54-6cf930de155a.png)

Design Mock:
*Note: There isn't a Phase 1 Design Mock for Routes, but Functions looks functionally equivalent. I assume the design would be as below, but also including a column with the HTTP verb and the routes data viz element shown in the JVM component:*
![image](https://user-images.githubusercontent.com/8700322/31727236-133c7a9c-b3f7-11e7-92ce-8fb6eb0380d4.png)

**Comment by lucasmoten** [comment]
I'd agree that its definitely important to denote the HTTP verb. Object Drive, and certainly other APIs, will give different meaning to the same route over a GET vs a POST vs DELETE etc.  Also taking into account CORS for OPTION preflights
