### ISSUE TITLE
Implement or Remove nonfunctional UI elements on service dashboard

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#605]
Most of the elements on the service dashboard are currently nonfunctional:
- Group By select
- Sort select
- Requests/sec field
- Error % field
- Uptime field
- Nothing is rendered in the content area of the sidebar.

These elements must be either implemented or removed prior to release.

![image](https://user-images.githubusercontent.com/8700322/31735801-f8e31a88-b410-11e7-80b9-639e2ab7b0cb.png)

**Comment by spmcbride1201** [comment]
@joshua-rutherford I'm tagging you on here as a continuation of our Slack discussion about metadata that we might be able to use to calculate some of these values. As I recall, you mentioned that there some technical differences between what was possible with Zookeeper nodes versus the discovery service, and you'd have to dig into it a bit more. I'd appreciate it if you could communicate findings here.

**Comment by spmcbride1201** [comment]
Generally, I'm assuming that `requests/s` and `Error %` would literally require something scraping each individual endpoint and rolling up the metrics, which is absolutely not feasible for MVP. It seems like Uptime might be able to be calculated in the browser if the service instances start time could somehow be provided. If that proved to be the case, I'd propose eliminating the Group By select and having a Sort select that sorts either by ID or by Uptime.

**Comment by joshua-rutherford** [comment]
I'm not clear on the requirement here.  Can you elaborate on the API requirements on the discovery service to make these functional?

1) Do you need me to provide sorting, grouping and paging? If so, which endpoints and fields?
2) Requests per second, uptime and error rate seem to already be available through the summary page for each instance so I'm not sure you need anymore from the backend, do you?

**Comment by spmcbride1201** [comment]
Happy to elaborate! 

I don't need sorting, grouping, or paging. We're doing all of that in front-end land.

Additionally, I'm not particularly attached to the metrics in this table because they would likely require something to manually roll them up in an ad-hoc way. This sort of thing wouldn't be possible on the front-end currently, as I've specifically restricted the dashboard to only be able to maintain the state of a single microservice instance at a single time to better protect against the dashboard running out of memory. I could backtrack on this and create some kind of fan-out async event that hits the metrics API for 1...n instances of a service and plucks out the required keys, but I am pretty opposed to architecting something so bandwidth, memory, and compute intensive for such a small payoff.

Given all those issues, I'm wondering what sort of metadata our service registry might maintain on the nodes that register as a service, and if it's worth presenting some of this metadata in this table (either directly or via computed properties I come up with on the front-end).

**Comment by spmcbride1201** [comment]
Per discussion with Josh, the tentative plan is to enhance the discovery-service to provide the start time of each instance. 
```
{
  "instances": [
     { "id": "4238686253fc34bf7c00f9a2b9c8f48a", "startTime": "15688372" }
  ]
}

On the client side, we'll use that to calculate Uptime just like on the instance dashboard.

In the design, we'll lose "Requests/s", "Error %", and the Group By dropdown. The sort option will allow sort by ID or Uptime.
