### ISSUE TITLE
Resolve Open Source License and validate implementation of terms and conditions

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#625]
We need to make a final decision about the open-source license we're going to be using for this project and add appropriate licensing documentation, including any required terms for our third-party modules. Currently, we are not using any copy-left dependencies. My personal suggestion is to go with the MIT license, which is much more of a community norm for front-end things versus something like Apache.

**Comment by spmcbride1201** [comment]
Also implicitly wrapped up in this is the question about open-sourcing supporting backend infrastructure like the `discovery-service`. My hope is that we can keep the direct supporting infrastructure similarly licensed.

**Comment by tilleryd** [comment]
![screen shot 2017-10-18 at 11 55 23 am](https://user-images.githubusercontent.com/2581080/31741537-950f7d46-b422-11e7-87fe-7ea31d86d78b.png)

**Comment by tilleryd** [comment]
![screen shot 2017-10-18 at 4 36 26 pm](https://user-images.githubusercontent.com/2581080/31741545-9d674e06-b422-11e7-8dff-192a1716a0c8.png)

**Comment by spmcbride1201** [comment]
Per verbal approval from @chrismholmes, we'll license this under MIT.
