### ISSUE TITLE
Testing: Round 1

### ISSUE THREAD

**Issue by tilleryd** [DecipherNow/gm-fabric-dashboard#626]
We need a solid round of testing from different folks in the company so we can get a better idea of where we are from the following topics:

1. cross browser support
2. bugs
3. intuitive user experience

I think a baseline sample of people is as follows:

- @7ruth   (4hrs) conducting cross browser testing (Chrome, Firefox, Safari, IE11) to ensure the application functions consistently between the browsers.
- @shindigira (2 hrs) and @brianlitalien (2 hrs) clicking through the app to identify any bugs or user experience issues.

Each person should collect their results and post them into a single comment into this issue for triage,

**Comment by spmcbride1201** [comment]
Feedback has been captured and decomposed into new issues, so closing.
