### ISSUE TITLE
Refactor sidebar cards so that spark lines don't get overlapped by metric values

### ISSUE THREAD

**Issue by tilleryd** [DecipherNow/gm-fabric-dashboard#627]
![screen shot 2017-10-18 at 4 39 08 pm](https://user-images.githubusercontent.com/2581080/31741644-f71e339c-b422-11e7-8bfc-e43769778fbd.png)

**Comment by spmcbride1201** [comment]
This issue is made redundant by the redesign of the primary nav element.
