### ISSUE TITLE
Service Instance View: unit test: HTTP view

### ISSUE THREAD

**Issue by tilleryd** [DecipherNow/gm-fabric-dashboard#631]

**Comment by karinakeen** [comment]
<img width="1276" alt="screen shot 2017-11-14 at 4 30 44 pm" src="https://user-images.githubusercontent.com/26534838/32806028-3a198192-c959-11e7-98a2-7a02bc8cbbd7.png">
HTTP view
<img width="1273" alt="screen shot 2017-11-14 at 4 30 35 pm" src="https://user-images.githubusercontent.com/26534838/32806024-37c9c974-c959-11e7-94d6-e7f7a22406c1.png">
