### ISSUE TITLE
Routes from other services appear in the "Routes" Tab

### ISSUE THREAD

**Issue by alecholmez** [DecipherNow/gm-fabric-dashboard#650]
Steps to recreate:
- Click team-service
- Click routes tab
- Go back to services
- Click POA
- Click routes tab
You will see team services routes in the routes tab even though POA only has functions.

**Comment by spmcbride1201** [comment]
@alecholmez - I'm struggling to reproduce this one. 

My steps:
1. Open the docs for the team-service and POA APIs and invoke GET requests
2. Go to Team Service and select services:
![image](https://user-images.githubusercontent.com/8700322/31962207-ec0c8100-b8ca-11e7-977e-409c6b86c047.png)
3. Go to POA and select services:
![image](https://user-images.githubusercontent.com/8700322/31962370-5ba06428-b8cb-11e7-83c8-71dfcb54c409.png)
4. Select functions in POA:
![image](https://user-images.githubusercontent.com/8700322/31962524-d0d7c0d8-b8cb-11e7-92d7-822ab8aa4229.png)

All of the responses from the API look sane to me, so I guess I'll take a look at the Redux reducers I'm calling when a user selects a new service.

**Comment by spmcbride1201** [comment]
@justincely or @joshua-rutherford. I couldn't recreate this issue. Can one of you take a look at this?

**Comment by justincely** [comment]
I actually saw this once the other day as well.  I was clicking back and forth between services and routes and was really surprised when the routes page for AAC showed the routes from one of the other go services i'd been viewing.  

Not sure if I can re-create, but i can try.

**Comment by spmcbride1201** [comment]
I spent some more time trying to re-create, but was unable to. After asking around, it sounded like this bug has not been recently encountered. Moving to the Great Beyond pending the bug reappearing.

**Comment by spmcbride1201** [comment]
Closing after not seeing this for several months. Will reopen if reported again.
