### ISSUE TITLE
Implement Error Boundary Components for major UI areas

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#657]
Example at https://hackernoon.com/error-boundaries-in-react-16-32fb8e185a3

**Comment by spmcbride1201** [comment]
@kaitmore and @7ruth - I'd like you to pair on this. In addition to the immediate objective, please take the opportunity to discuss styled-components and React component lifecycle hooks. The learning objective for Martin is for him to be able to explain the React component lifecycle, understand how styled-components generated components differ from class-based and stateless functional components, and understand how writing stylesheets via styled-components differs from writing a *.css file by hand. I'd like Martin to write short responses to these issues, so we can start building up content in our Decipher front-end wiki

**Comment by kaitmore** [comment]
Resolved by #693
