### ISSUE TITLE
Implement Interaction Appearance Templates

### ISSUE THREAD

**Issue by shanberg** [DecipherNow/gm-fabric-dashboard#665]
Create CSS templates to include in interactable elements such as links, cards, buttons, and form elements, to be included as common interaction formats for otherwise disparate UI elements. In essence a Styled Components reimplementation of HTML classes or preprocessor mixins.

As SCSS it might look like this...
```
$baseLinkColor: blue;

.interactionModeLink {
  color: $baseLinkColor;

  &:hover {
    color: lighten($baseLinkColor, .2);
  }

  &:active {
    color: darken($baseLinkColor, .2);
  }

  &.active {
    color: darken($baseLinkColor, .4);
  }
  ...
}
```

This set of styles would be included in every UI element we wanted to appear as a standard link.

**Comment by spmcbride1201** [comment]
Duplicated of #728
