### ISSUE TITLE
Enable use of custom themes in dashboard

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#67]
Custom Company Logo
Custom Font
Custom Contrast Values

"instead of defining the colors of interface elements with hex codes, I think we should define them with intended contrast values. 

E.g. text is contrast .9. 
If you set background to white, text is rgba(0,0,0,.9)
If you set background to black, text is rgba(255,255,255,.9)

well the opacity is half of the contrast, the other functional element is the base color, white or black
color = --content-color
contrast = .9
but the point is to make the color implicit
set your content color
set your highlight color (like bright blue or bright green or something)
then for individual elements, just set a contrast value
strong, muted, light, or a floating point or such
then in the layout, set background color for page sections
a color-inverted section uses the content-color as the background, and reversed the color used in the text/content itself, but retains the same contrast value"

**Comment by chrismholmes** [comment]
One thing here, we don't want to make this so easy that it becomes easy to completely remove Decipher branding.  We should at least in the footer state something like Copyright Decipher Technology Studios, Powered by Grey Matter and perhaps three dots.

**Comment by spmcbride1201** [comment]
@shanberg I think we should do some concept mocks for:
- Vanilla Open Source that lives in this repo
- Custom decipher dash that we theme using non open-source stuff like Avenir Next and bundle into our premium products
- Custom white label including ACME Co logo in relation to Decipher logos and "Powered by Grey Matter" attributions / trademarks. I am curious about the possible differences between white-labeling the vanilla open source versus the premium dash.

**Comment by chrismholmes** [comment]
Right now, we do not differentiate what is open source and what is premium.  It is all Grey Matter and the current plan is that everything is going open source.

**Comment by shanberg** [comment]
@chrismholmes The biggest issue here is how to handle licensed brand resources like Avenir Next, which we can't push into an open source repository, but is part of Decipher's look and feel and part of how we present Grey Matter.

Theme customization of the Fabric Dashboard can be thought of as merely a means of implementing the most superficial elements of look and feel (Decipher Green, and the Avenir Next type family) without also having to deal with the licensing issues that Avenir Next brings with it.

We don't plan on inviting admins to strip out attribution or meaningfully change the user experience with custom CSS etc., we just need to resolve the fact that we legally can't push fonts we don't own into an open source repository.

By adding a thin layer of theme customization, we can open source the GM Fabric Dashboard and present it with Decipher branding, without having to pay out the nose for a custom enterprise license to a font.

When a new user pulls and runs GM Fabric Dashboard, all that we intend to be different from screenshots and demos at this point is a different font.

**Comment by spmcbride1201** [comment]
This scope of work is impacted with #103. Based on recent discussions around setting Decipher look and feel via an external JSON file, the architecture used to build a Decipher Bootstrap theme will likely handle some of these requirements.
