### ISSUE TITLE
Delete unused SCSS rulesets

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#672]
It seems like about 1/3 of our SCSS code is rules tied to selectors that don't seem to be used in the project. This is bloating our CSS bundle. The scope of this task is to identify and remove selectors that aren't matching anywhere in the application. It should be sufficient to search the project for classnames and delete whatever isn't being used.

**Comment by shanberg** [comment]
Closed by #700
