### ISSUE TITLE
Fabric-Go-Service-Sidebar-Routes does not display number of requests 

### ISSUE THREAD

**Issue by karinakeen** [DecipherNow/gm-fabric-dashboard#673]
Edge

<img width="462" alt="screen shot 2017-10-24 at 10 09 25 am" src="https://user-images.githubusercontent.com/26534838/31947918-73e19e1c-b8a3-11e7-8c3b-ef441badc174.png">

Master

<img width="388" alt="screen shot 2017-10-24 at 10 10 20 am" src="https://user-images.githubusercontent.com/26534838/31947971-969e2646-b8a3-11e7-86e1-e3734f411a9e.png">

**Comment by spmcbride1201** [comment]
Reassigning to align to @kaitmore and @shanberg 's work on the new nav elements. I'm unclear on if this bug would carry over via code reuse of the SummaryCard stuff or if this might just end up getting fixed as the new elements are built out.

**Comment by spmcbride1201** [comment]
Validated that this issue is still active in the new layout.
