### ISSUE TITLE
Long card titles overflow

### ISSUE THREAD

**Issue by kaitmore** [DecipherNow/gm-fabric-dashboard#674]
When a card title is too long it needs to be truncated

![screen shot 2017-10-24 at 10 11 44 am](https://user-images.githubusercontent.com/22768918/31948137-0ed2c36a-b8a4-11e7-9658-67bcf363e3b9.png)

**Comment by shanberg** [comment]
We'll need to truncate the text in the markup here, unless we want to allow cards to grow. There's no way in CSS to use an ellipsis to limit vertical flow.

**Comment by spmcbride1201** [comment]
@shanberg - That sounds like a good approach to me. 👍

**Comment by spmcbride1201** [comment]
Reassigning to @7ruth. Martin, please tag @shanberg and either Kait or Karina as reviewers on your PR.
