### ISSUE TITLE
Refactor Storybook stories into the component file structure

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#677]
The intention here is that the stories for each component should reside inside of the component's directory, rather than in a top-level `/stories` directory. For example, stories for `AppToolbar` would reside in a file at `/src/components/Main/components/AppToolbar/index.stories.js`.

If the storybook was just targeting a single styled-component, there wouldn't be a directory, so the stories would reside in the same `components` directory as the styled-component with the same name and a `.stories.js` suffix. E.g. `awesome.js` would be accompanied by `awesome.stories.js`.

Instructions for configuring this are at https://storybook.js.org/basics/writing-stories/#loading-stories-dynamically

**Comment by kaitmore** [comment]
Resolved by #671

**Comment by spmcbride1201** [comment]
Related to fixing #785. Escalating to priority 1 and reassigning to me.
