### ISSUE TITLE
Fatal error when updating submodules in the git repo

### ISSUE THREAD

**Issue by jsweetland** [DecipherNow/gm-fabric-dashboard#678]
An error stating "fatal: No url found for submodule path 'docker/docker-graphite-statsd' in .gitmodules" is thrown when the following command is run (note: this command is automatically run in Sourcetree when performing a pull operation).

Command: `git -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree submodule update --init`

**Comment by joshua-rutherford** [comment]
That commit has your name on it @spmcbride1201.  I'm not sure this one belongs to me, but I could be wrong.

**Comment by spmcbride1201** [comment]
I've never created a submodule in my life, but I'll take a look.
