### ISSUE TITLE
CI should fail the build if any of the storybook stories don't render as expected.

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#682]
I believe that the proper approach for ensuring that changes to UI components don't break storybook is to implement Storyshots as outlined in https://github.com/storybooks/storybook/tree/master/addons/storyshots

My intention here is that the storyshots would be run alongside all other Jest tests that fire when we run `npm test`. This also means that we gain rudimentary UI testing for all UI components that have associated stories.

**Comment by kaitmore** [comment]
@spmcbride1201 let me know if you still want me to implement this
