### ISSUE TITLE
Gray/Grey discrepancies

### ISSUE THREAD

**Issue by jsweetland** [DecipherNow/gm-fabric-dashboard#684]
The title of the pages is "Gray Matter" in the American spelling while the text in the bottom of the sidebar reads "Grey Matter" in the preferred British spelling.

**Comment by spmcbride1201** [comment]
![](https://media.giphy.com/media/xT5LMwDv8zquNq1Qdi/giphy.gif)

**Comment by shanberg** [comment]
The official spelling is "Grey Matter".
