### ISSUE TITLE
Test use of PurifyCSS as a means to reduce the size of the CSS bundle (including UIKit)

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#689]
Currently our project is generating a bundled stylesheet from:
- an import pulling in all of UIKit
- a bunch of SCSS and CSS located in `/src/styles`
- Various Styled components in the app

UIKit and the SCSS/CSS stuff have a bunch of classes that we aren't using. While we want to refactor this stuff out of the project eventually, this won't happen in time for our initial customer release. As an interim solution to reduce the size of the CSS bundle, we should consider adding PurifyCSS into our production webpack config.

The scope of this issue is to attempt adding this tooling, determining if we are able to add it without breaking things, and measuring the size reduction of the CSS products by `npm run build`. Depending on this effort turns out, this feature branch may or may not be merged into master.

https://github.com/webpack-contrib/purifycss-webpack

**Comment by spmcbride1201** [comment]
@7ruth and @kaitmore - Please pair on this. The driver should attempt to understand what's going on in our webpack configs and the navigator should be at-the-ready with the docs for webpack, babel, purifycss, etc.

**Comment by kaitmore** [comment]
Closed (reference: https://github.com/DecipherNow/gm-fabric-dashboard/pull/857#issuecomment-342679955 )
