### ISSUE TITLE
Address Accessibility Issues flagged by Chrome Lighthouse Tool

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#690]
While we currently have a reasonable rating for a11y based on the Chrome Lighthouse Tool, there do seem to be a few issues. Please address these issue to raise the score and open followup issues for major accessibility issues that you encounter. You can rerun Lighthouse via the Audit tab in Dev Tools.

![image](https://user-images.githubusercontent.com/8700322/31967525-25e36fc2-b8dc-11e7-8408-56eb874cc2a3.png)

**Comment by 7ruth** [comment]
One of the issues flagged by the Lighthouse is due to react-select added div next to our drop down filters not having aria-owns attribute (related issue on react-select github https://github.com/JedWatson/react-select/issues/1544 )

**Comment by spmcbride1201** [comment]
Holy smokes, so you're saying `react-select` is essentially inaccessible?

**Comment by 7ruth** [comment]
Not exactly, there are just slight issues with it. I tested that box with mac's voiceOver and you can navigate it and it tells you options, but the issue is when you select the option, the box doesn't tell you what option is currently selected. I'd say thats pretty accessible but not perfect.

**Comment by 7ruth** [comment]
@spmcbride1201 ran the lighhouse tool on all the pages... we don't get below 86 on any of them. 
There are only 3 things that remain that would get us to 100 across all the pages:
1. React-select related flags are responsible for most of the reduction in our score
2. Contrast on few elements (grayed out elements such as version and copyright). For some reason, despite my tweaks, they still get flagged (we get 97 on those pages)
3. There are some pages where glyph contents have same ids and that gets flagged (unique IDs), I expect this to be solved by my/Karina/Stuart refactoring on those svgs.
