### ISSUE TITLE
Fix Metrics Cache Size Settings Widget

### ISSUE THREAD

**Issue by shanberg** [DecipherNow/gm-fabric-dashboard#701]
![image](https://user-images.githubusercontent.com/8700322/32107280-1fcefd46-bafc-11e7-9b27-f3915a3de555.png)

**Comment by shanberg** [comment]
May need to build new type of component to contain the Metrics Cache Size information and reset button. As it is, the widget is stretched and difficult to read.

**Comment by spmcbride1201** [comment]
![](https://media.giphy.com/media/ly8G39g1ujpNm/giphy.gif)

**Comment by spmcbride1201** [comment]
Closing as the solution to this is a duplicate of #602, which I'll bump up to a priority 1 bug to reflect the fact that it's currently broken.
