### ISSUE TITLE
Authorization Redirect always fires on hard refresh

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#706]
When a user goes to a route and issues a hard refresh, the user is immediately redirected to the root route and presented with a "You are not authorized." message. This includes microservices that the user actually is authorized to see.

![image](https://user-images.githubusercontent.com/8700322/32022803-7d21dcb4-b9a5-11e7-9688-d8bc0194c24c.png)

**Comment by kaitmore** [comment]
Closed by #856
