### ISSUE TITLE
Different HTML structure for services that are not authorized

### ISSUE THREAD

**Issue by jsweetland** [DecipherNow/gm-fabric-dashboard#712]
The HTML structure for the services cards is different depending on whether the service is authorized. Authorized services consist of an `a` tag containing the name and a `div` tag containing the version and a link, while non-authorized services consist of a `div` tag containing the name and a second `div` tag containing the version and link.

**Comment by karinakeen** [comment]
![screen shot 2017-10-26 at 11 34 46 am](https://user-images.githubusercontent.com/26534838/32062170-b561d3bc-ba41-11e7-8874-aca4aef36d39.png)

change pointer to "not-allowed" for "not authorized" service even if the service is not "down"

**Comment by jsweetland** [comment]
I filed the mouse cursor issues separately as #713, but we can combine them if that makes more sense.

**Comment by shanberg** [comment]
Should these services have something more to indicate user isn't authorized to inspect? Like a lock icon before the title?

**Comment by spmcbride1201** [comment]
@shanberg - I think that's a good idea. There's a bit more nuance to the API about why an item might be clickable (you might not be authorized or the service may not be instrumented). I'll open a new issue to discuss ideas for how to express this in card and table view.

**Comment by spmcbride1201** [comment]
@jsweetland - Now that we've broken out issues for the cursor and the UI cues to demonstrate why something isn't clickable, I'm not sure what the action is here. Is the differing HTML structure blocking your ability to write Selenium tests now? Just trying to figure out the action or if we can close this issue.

**Comment by jsweetland** [comment]
It's not blocking test writing, I'll just need to account for the differences. There may not be an action here, just wanted to make sure that the differences between authorized and non-authorized services weren't intended to be expressed only through CSS and that actual structural differences were intended.

**Comment by spmcbride1201** [comment]
Okay, cool. They are intentional.
