### ISSUE TITLE
Change mouse cursor to the prohibition sign when hovering over non-authorized services

### ISSUE THREAD

**Issue by jsweetland** [DecipherNow/gm-fabric-dashboard#713]
When hovering the mouse over services on the main dashboard page which are not authorized, the mouse cursor should change to the prohibition sign.

**Comment by spmcbride1201** [comment]
Specifically `cursor: not-allowed;`

https://developer.mozilla.org/en-US/docs/Web/CSS/cursor

**Comment by shanberg** [comment]
Closed by #641
