### ISSUE TITLE
Uptime value in the sidebar does not match value on page

### ISSUE THREAD

**Issue by jsweetland** [DecipherNow/gm-fabric-dashboard#714]
The uptime value shown in the sidebar does not match the uptime value shown on the main page. Discovered in the f5nqgzxp4e8000000000 instance of Network Internet Information service, see screenshot.
![screen shot 2017-10-26 at 1 18 05 pm](https://user-images.githubusercontent.com/7924822/32067272-a3c9c7a4-ba50-11e7-8aee-74556e1f5b75.png)

**Comment by spmcbride1201** [comment]
woah. How in the world is an 80 day discrepancy possible? This makes me suspect that something larger might be going on with stale date from that last loaded dashboard.
