### ISSUE TITLE
Threads value in the sidebar does not match value on page

### ISSUE THREAD

**Issue by jsweetland** [DecipherNow/gm-fabric-dashboard#715]
The Threads value shown in the sidebar does not match the Threads value shown on the main page. Discovered in the f5nqgzxp4e8000000000 instance of Network Internet Information service, see screenshot.
![screen shot 2017-10-26 at 1 38 09 pm](https://user-images.githubusercontent.com/7924822/32068053-293d512e-ba53-11e7-9775-ec931d24d438.png)

**Comment by spmcbride1201** [comment]
Seems related to #80, which was closed a while back. It might be worth taking a look at the commits targeting that fix to figure out what I missed.

**Comment by spmcbride1201** [comment]
May be related to stale data due to messed up React component lifecycle methods and thereby related to #714
