### ISSUE TITLE
Fabric Page: Empty groupings should not be displayed

### ISSUE THREAD

**Issue by shanberg** [DecipherNow/gm-fabric-dashboard#723]
On the Fabric page in a Cards view, with Group: Status and Sort: Name, if the Down and Warning groups are empty, I think we should hide them from the view.

There are probably other things we should do in this case, but I can't think of them at the moment.

**Comment by spmcbride1201** [comment]
I concur that this is a good idea. Only do this in the Main view area, not the sidebar, as the sidebar is going to be zapped anyways.

**Comment by 7ruth** [comment]
This also needs to be implemented on list view
