### ISSUE TITLE
Visual Indicators for Cards and Tables to demonstrate why something isn't selectable

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#725]
The API currently has keys called `authorized`, `threaded`, and `metered`.

`authorized: false` means that your user isn't allowed to view the microservice

`metered: false` means that the microservice doesn't offer the metrics that we need to build a dashboard

`threaded: false` means that the microservice doesn't offer the special stack trace data that we use to build out the "Threads" component.

All of these values are populated differently, so you can be authorized to view a microservice that doesn't have metrics for example.

I believe that the logic that we card about on the Fabric dashboard is checking that a microservice has metrics and that the user is authorized to view the dashboard showing these metrics. Threaded is a bit different, so it probably has no impact on navigation from the Fabric dashboard.

It probably makes sense to depict to a user why a card or table item isn't selectable:
* Not authorized
* No metrics
* Not authorized and no metrics

If we only want to show one icon, then Not Authorized seems like a higher priority than No Metrics.

**Comment by shanberg** [comment]
![screen shot 2017-10-27 at 11 32 51 am](https://user-images.githubusercontent.com/98312/32112199-9801ba66-bb0a-11e7-8665-26f77dd9ca82.png)

My current thinking for what to display directly in the card:
- No-authoriziation icon if user isn't authorized to manage
- No-metrics icon if no metrics are available

Each icon should pop a tooltip describing what it means, and potentially at some point in the future we could link to more information about service states and conditions.
