### ISSUE TITLE
return key doesn't work on firing individual service from fabric - table view - service

### ISSUE THREAD

**Issue by karinakeen** [DecipherNow/gm-fabric-dashboard#729]
1/ On fabric - table view - service

Services is highlighted but keypress event does not fire.

<img width="1385" alt="1" src="https://user-images.githubusercontent.com/26534838/32107433-8ca5e0e2-bafc-11e7-939e-8623f091b820.png">

2/ On fabric -table view - service - instances
adding a minor bug to this issue as well - the keypress event works, but selected instance doesn't appear 'highlighted' on tale view- service- selecting an individual instance

<img width="1014" alt="2" src="https://user-images.githubusercontent.com/26534838/32107472-b1d2a7ba-bafc-11e7-9b11-3daa0b5471d9.png">

**Comment by 7ruth** [comment]
fixed by #771
