### ISSUE TITLE
Routes Table Line Item Error % Issues

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#745]
1. The error % is resolving to NaN in some cases
2. The error % is using a yellow color that is very hard to make out on a white background.

Note: this was seen in a JVM microservice, but it likely is also occurring with other runtimes.

![image](https://user-images.githubusercontent.com/8700322/32186379-501507b0-bd78-11e7-9bf7-fc867d75500e.png)

**Comment by karinakeen** [comment]
@spmcbride1201 @shanberg Which colors do you want against white/black background for stable/warning/error?

**Comment by spmcbride1201** [comment]
I defer to @shanberg on this.

**Comment by karinakeen** [comment]
blocked by #782
