### ISSUE TITLE
When sorting by Error % or Latency, the default sort should be high to low

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#746]
Currently, when a user selects sort by Error % for our tables, the top result is the lowest error rate. This order should be flipped. This should be the same for latency metrics as well.

**Comment by karinakeen** [comment]
@spmcbride1201 We have sort by Error %??

**Comment by spmcbride1201** [comment]
Per verbal discussion, please open a new issue to refactor the Go dashboards so that they have Sort By Error % in place of Sort by Error Count for the Functions and Routes dashboards. Thanks!
