### ISSUE TITLE
Focus color is the same as select color, which makes it hard to tell where focus is

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#752]
Focus on Cards with Cards selected
![image](https://user-images.githubusercontent.com/8700322/32188948-9df34314-bd7f-11e7-8c38-aede1653a2b2.png)

Focus on Table with Cards selected
![image](https://user-images.githubusercontent.com/8700322/32188963-ac84d280-bd7f-11e7-85ab-80d6b0b003ce.png)

Focus on Table with Table selected
![image](https://user-images.githubusercontent.com/8700322/32189012-d6f3fdde-bd7f-11e7-96af-4e14616763b0.png)

**Comment by shanberg** [comment]
Closed by #835
