### ISSUE TITLE
Spacebar does not select select links, only enter

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#754]

**Comment by kaitmore** [comment]
@spmcbride1201 Got stuck on this one. Tried multiple ways to grab value from dropdown while using an onKeyDown/onInputKeyDown event to allow spacebar selection.

**Comment by spmcbride1201** [comment]
Ok, I don't particularly think this is a big enough deal. We have some variance in our keyboard controls, but at lease we have them. Bumping to great beyond.
