### ISSUE TITLE
React Select dropdowns has something rendering on top in Safari, Firefox, IE.

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#758]
![image](https://user-images.githubusercontent.com/8700322/32190536-7e0ab2bc-bd84-11e7-8f3e-0eacdcedaef1.png)

**Comment by kaitmore** [comment]
@shanberg This is a stacking issue with the new stick headers

**Comment by shanberg** [comment]
@spmcbride1201 What page did you find this on?

**Comment by shanberg** [comment]
Addressed by #810

**Comment by shanberg** [comment]
Noticed this reoccurring.
