### ISSUE TITLE
UX suggestion: always show SummaryBarCard

### ISSUE THREAD

**Issue by tilleryd** [DecipherNow/gm-fabric-dashboard#77]
I stopped polling and cleared metrics cache which made the summary bar cards disappear longer than expected.  It would be nicer to keep the cards there and just shows zeroed out values.
If the user sets polling to 2 minutes they won't see the cards until data is fetched.

**Comment by spmcbride1201** [comment]
Closing this ticket, as the behavior is essentially moot with the dashboard model.
