### ISSUE TITLE
The settings cog icon disappears when you zoom in at 200% with your browser

### ISSUE THREAD

**Issue by 7ruth** [DecipherNow/gm-fabric-dashboard#777]
The settings cog should be visible at any zoom level.
At 100%
<img width="1180" alt="screen shot 2017-10-31 at 2 45 48 pm" src="https://user-images.githubusercontent.com/10719152/32242883-46a21ac4-be4a-11e7-870e-21085e1d09fa.png">
at 175%
<img width="1008" alt="screen shot 2017-10-31 at 2 46 09 pm" src="https://user-images.githubusercontent.com/10719152/32242893-4b8738d0-be4a-11e7-8600-11884b3bd03f.png">

As you can see, at high zoom, the settings cog is missing.

UPDATE (based on the latest master):
At 200% zoom, the cog is not visible and the y-axis scroll bar does not appear at that zoom level. 

The y-axis scroll bar should appear when content falls offscreen.

**Comment by karinakeen** [comment]
blocked by #768.  wait to confirm flexbox behavior until new app header is integrated.

**Comment by karinakeen** [comment]
@7ruth is the end goal having the cog button sit on top of a long path?

**Comment by 7ruth** [comment]
@karinakeen thats what I was thinking, or you also had a good suggestion when we looked at it, where you said that a horizontal scroll bar appears at high levels of zoom. Ultimately, the cog should still be accessible in some way when you get to 200% + zoom.

**Comment by 7ruth** [comment]
Resolved by #848
