### ISSUE TITLE
storybook is broken

### ISSUE THREAD

**Issue by karinakeen** [DecipherNow/gm-fabric-dashboard#785]

**Comment by karinakeen** [comment]
after src is added as a modules directory,  `/src` directory is throwing error when called from `/stories`, outside of `/src` directory.

<img width="657" alt="screen shot 2017-10-31 at 11 59 14 pm" src="https://user-images.githubusercontent.com/26534838/32259635-2bfb4fa8-be98-11e7-8db9-2f7919daf0c1.png">

<img width="1270" alt="screen shot 2017-10-31 at 11 58 49 pm" src="https://user-images.githubusercontent.com/26534838/32259641-30cc85c4-be98-11e7-9328-888ff038c1a7.png">

**Comment by 7ruth** [comment]
looking into this...

**Comment by kaitmore** [comment]
@7ruth @spmcbride1201 @karinakeen  Perhaps we should hold off on this. My ginormous PR also touched a lot of storybook stuff and I think it will be merged soon.

**Comment by karinakeen** [comment]
blocked by #768

**Comment by spmcbride1201** [comment]
Hey all, I'm taking this on because it sounds like my Webpack black magic broke this.
