### ISSUE TITLE
Replace sparklines data & line items in Fabric view tabs

### ISSUE THREAD

**Issue by kaitmore** [DecipherNow/gm-fabric-dashboard#786]
Currently, the sparklines data in the fabric view tabs is just displaying # of microservices, which is not very interesting.

<img width="1424" alt="screen shot 2017-10-31 at 4 49 01 pm" src="https://user-images.githubusercontent.com/22768918/32248255-76214980-be5b-11e7-951c-4534e76cb8d4.png">

**Comment by spmcbride1201** [comment]
I literally have no idea what sort of metrics would make sense here. I can't think of any data that we have that would be helpful to the user in this context.

**Comment by spmcbride1201** [comment]
@tilleryd - Any ideas?

**Comment by shanberg** [comment]
If there's no useful data to display, then this is my problem to fix. I'm not happy with the way these tabs look when there's just a title and single detail line, but maybe it'll improve when icons are in place.

**Comment by shanberg** [comment]
Once we have proper icons in place, lets remove the sparklines.

![screen shot 2017-11-06 at 4 31 54 pm](https://user-images.githubusercontent.com/98312/32465026-11debe26-c310-11e7-86af-aca92f63b98c.png)
