### ISSUE TITLE
Center main content body

### ISSUE THREAD

**Issue by kaitmore** [DecipherNow/gm-fabric-dashboard#792]
<img width="520" alt="screen shot 2017-11-01 at 10 24 11 am" src="https://user-images.githubusercontent.com/22768918/32279336-d8a9839a-beee-11e7-8278-2ae474cb69b0.png">

**Comment by shanberg** [comment]
- [ ] Proper width on Toolbars
- [ ] Proper width on Fabric Grid
- [ ] Proper width on All Tables
- [ ] Proper width on Service Summary
- [ ] Proper width on Grid pages, charts and tables
- [ ] Proper width on Explorer

**Comment by shanberg** [comment]
Closed by #809
