### ISSUE TITLE
Sparklines actually go over toolbar

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#800]
Kinda hard to see, but the sparklines are half covering the toolbar.

![image](https://user-images.githubusercontent.com/8700322/32285582-1a67f9ee-bf01-11e7-9b6b-923eecf14a99.png)

**Comment by kaitmore** [comment]
@shanberg I feel like you were working on this before right? Any advice?

**Comment by kaitmore** [comment]
@spmcbride1201 Letting @shanberg handle this one since he has a solution
