### ISSUE TITLE
Uptime in service instance list view does not match instance summary view

### ISSUE THREAD

**Issue by karinakeen** [DecipherNow/gm-fabric-dashboard#850]
<img width="897" alt="screen shot 2017-11-03 at 3 21 39 pm" src="https://user-images.githubusercontent.com/26534838/32392160-d084683e-c0aa-11e7-9188-0a63707371b3.png">

<img width="911" alt="screen shot 2017-11-03 at 3 21 25 pm" src="https://user-images.githubusercontent.com/26534838/32392163-d5e1ea4a-c0aa-11e7-9cb8-054e211e4dae.png">

Related to #714

**Comment by spmcbride1201** [comment]
This is technically coming from two different metrics, which aren't logically set in our mock data apparently. The first image is coming from the `jvm/start_time` that we have direct access to and the second is coming from the `start_time` key on an instance object returned by the `/services` route. I think this value is coming from when a microservice registers as available with our Fabic-wide configuration management service. 

```js
{
	"name": "Discovery Service",
	"version": "1.0",
	"owner": "Decipher",
	"capability": "Service Discovery",
	"runtime": "JVM",
	"documentation": "https://edge.deciphernow.com/services/discovery-service/1.0/home.html",
	"minimum": 1,
	"maximum": 1,
	"authorized": true,
	"metered": true,
	"threaded": true,
	"instances": [{
		"name": "1e5afe0eca4cd9a66a1ecfc48bdfcaff",
		"start_time": 1509992134315
	}]
}
```

Looking on edge, the `start_time` key on an instance object returned by `/services` seems to be about a minute later than `jvm/start_time`. This seems logical to me given the time it takes for a microservice instance to register with our Fabric as available.

This behavior seems okay to me for now, but it might be worth semantically differentiating these uptime values in the future.
