### ISSUE TITLE
Unit test for threadsCount library component

### ISSUE THREAD

**Issue by karinakeen** [DecipherNow/gm-fabric-dashboard#851]
Write a unit test for threadsCount library component, issue #715 
 
1. using mock metrics data update the store
2. test that the header threadscount has the expected value
3. test that the JVM threadscount tab has the expected value

**Comment by spmcbride1201** [comment]
Is this something that you've already started? I think some of these components might be impacted by changes around #610.

**Comment by karinakeen** [comment]
@I started this yesterday but no solid progress with enzyme mount issues.

**Comment by spmcbride1201** [comment]
@karinakeen - I'm just saying I think that the threadsCount stuff might get refactored and the stuff you're proposing to test might get refactored out of the project, so this should be considered blocking until #610 is complete.

**Comment by karinakeen** [comment]
@spmcbride1201 sounds good.

**Comment by kaitmore** [comment]
@spmcbride1201 pretty sure this is irrelevant now ^^

**Comment by spmcbride1201** [comment]
Yep, closing
