### ISSUE TITLE
Threads seem to have a fixed height, which is either too long or too short depending on length of stacktrace

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#873]
![image](https://user-images.githubusercontent.com/8700322/32458553-c78d6d5a-c2fa-11e7-8534-15c3b5390a5d.png)

**Comment by tilleryd** [comment]
@spmcbride1201 @shanberg There's a couple ways we can do this:

1) Keep the accordion at a fixed height and add scrolling if the stack trace overflows.
2) Increase the height to a set threshold for long stack traces to provide more vertical reading space.  Scrolling can still be applied when the stack trace overflows the threshold.

**Comment by spmcbride1201** [comment]
Why can't we just restore the previous functionality of a variable height drawer with a size equal to the child stack trace? Do you not like that from a UX perspective?

**Comment by kaitmore** [comment]
Closed by #954
