### ISSUE TITLE
Add icons to the tabs as shown on the phase 1 mocks

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#881]
Fabric Dashboard:
![image](https://user-images.githubusercontent.com/8700322/32465470-8f71b8ec-c311-11e7-92d9-0b295603b942.png)
Service Dashboard
![image](https://user-images.githubusercontent.com/8700322/32465492-a4422234-c311-11e7-8a29-8525a3bd956e.png)
Instance Dashboard (ignore the configuration tab and use JVM and Go runtime icons as needed)
![image](https://user-images.githubusercontent.com/8700322/32465514-b856ee44-c311-11e7-86d3-73e06616d1c9.png)

**Comment by karinakeen** [comment]
@shanberg Do we have icons/glyphs for `Routes` and `Go`?  They are defaulting to Summary now.  

<img width="908" alt="screen shot 2017-11-08 at 9 17 20 am" src="https://user-images.githubusercontent.com/26534838/32553719-ab8e5a44-c465-11e7-9d0d-2c5249724d38.png">

same for `Routes`, `JVM` and `Finagle`
<img width="934" alt="screen shot 2017-11-08 at 9 18 26 am" src="https://user-images.githubusercontent.com/26534838/32553791-d4997586-c465-11e7-90c3-37032496cad5.png">
