### ISSUE TITLE
The Uptime Component loads twice for Go microservices

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#882]
The Uptime component loads once for JVM, but twice for Go. Loading twice is pretty jarring.

Demo of behavior:
https://youtu.be/3kIiYQ8N7Uo

**Comment by kaitmore** [comment]
@spmcbride1201 I'm not noticing this behavior anymore

**Comment by spmcbride1201** [comment]
@kaitmore Same here. Not sure if it's a timing thing due to the lazy loading of the split bundles or what, but I'm not seeing it. Can I push this out to the great beyond and deassign you? I have a suspicion we might see this again in the future under the right conditions.

**Comment by spmcbride1201** [comment]
Closing this because I can't recreate on edge. Will re-open if I see this again.

**Comment by kaitmore** [comment]
Resolved by #1391
