### ISSUE TITLE
Create Fabric Shortcuts

### ISSUE THREAD

**Issue by 7ruth** [DecipherNow/gm-fabric-dashboard#887]
When I was an analyst at a bank, we lived and breathed Excel and one thing that was instrumental to high productivity were SHORTCUTS. 

I propose that we implement shortcut key combinations to the Fabric platform to accelerate user's ability to navigate the app and extract useful data. 

Example: (due to Tab and Shift+Tab being primary ways to navigate, shortcut combos should be close to those buttons)
Landing Page: use Ctrl+ (q,w,e,r) to navigate between ribbon headings. 
Ctrl+S can be used to immediately jump to the search box. 
Crlt+D (for example) then can be used to jump to the first search result (instead of pressing tab 4 times). This can also be used on all other screen to jump to the first clickable result (aka an instance within service instances view)

Sean suggested that we could also wire some key combos to zoom in and out of the graphs.

**Comment by spmcbride1201** [comment]
![](https://media.giphy.com/media/cFdHXXm5GhJsc/giphy.gif)

**Comment by lucasmoten** [comment]
Are you joking?

I propose NOT using keyboard combinations like this that are already reserved and in heavy use for other core functions

CTRL + Q = Quit the Application
CTRL + W = Close the Window (can also quit the application)
CTRL + E = Goes to the web search bar
CTRL + R = Refresh Page (like F5)
CTRL + S = Save the current file
CTRL + D = Bookmark the page

**Comment by spmcbride1201** [comment]
Be nice! Probably slipped Martin’s mind because the Mac has the command key / the reference app (Excel) is a native app / he wrote this at hour 10 of his workday. We won’t overload native shortcuts, and we’d look at other web and Electron apps for inspiration about which keys to use.

**Comment by lucasmoten** [comment]
That's fair. If there are keyboard shortcuts added, we have some liberty on making them different for platform as well.  The combinations above are mainly Windows shortcuts. I assume these differ from counterparts on the Mac and Linux. 

Funny story about this .. I used to routinely use CTRL+Q in Microsoft Outlook to mark selected messages as read.  Switching to Linux, my email client there ended up closing the application (without warning) in that scenario. Obviously not the action I had in mind.  It took me a few times experiencing that to retrain my brain and having frustrations on the actions of CTRL+Q.  Nowadays, both Chrome and Firefox provide mechanisms for disabling that binding.

[Chrome shortcuts](https://support.google.com/chrome/answer/157179?hl=en)  (yes, they vary depending on linux, windows or mac)

**Comment by spmcbride1201** [comment]
I still think this is a good idea, but I think this is likely too far out on the project roadmap to justify keeping open an issue. I'll reopen this as the product roadmap allows.
