### ISSUE TITLE
Error in console when navigating to GO instance Routes tab

### ISSUE THREAD

**Issue by 7ruth** [DecipherNow/gm-fabric-dashboard#897]
<img width="808" alt="screen shot 2017-11-07 at 3 44 50 pm" src="https://user-images.githubusercontent.com/10719152/32516839-b1185c32-c3d2-11e7-9443-13c7a128c67c.png">

**Comment by spmcbride1201** [comment]
Thanks for reporting this!!

**Comment by 7ruth** [comment]
Resolved by #928
