### ISSUE TITLE
Update ReadoutItemIcon to accept a Glyph as content

### ISSUE THREAD

**Issue by shanberg** [DecipherNow/gm-fabric-dashboard#898]
`ReadoutItemIcon` currently receives a string corresponding to an icon in the UIKit library. We need to be able to render an `Icon` containing a `Glyph` from our own library.

**Comment by spmcbride1201** [comment]
We need to handle a Glyph generated from a string via the abstract Glyph component and also any arbitrary Glyph component passing in. This means that I should be able to pass a glyph into ReadoutItemIcon as a child, and it should be passed through as a child of Icon. 

A Glyph should always be required to be passed in as a child to allow the developer to choose to pass a custom Glyph component or the abstract Glyph component that uses a string to figure out what to render.

**Comment by karinakeen** [comment]
@spmcbride1201   This arbitrary Glyph component as Props.children is going to be a single child component or array of components.  Checking props.children as a valid Glyph component sounds tricky, I can check for `path` or `g` elements, but doesn't guarantee it will actually render?

**Comment by karinakeen** [comment]
@spmcbride1201 The developer will have to signal that they are passing in their custom glyph component...or should I assume if there is a props.children == glyph component?
