### ISSUE TITLE
Purge Docker Dev NGINX Certs

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#952]
We currently have certs checked into the git repo for our Docker development environment.

![image](https://user-images.githubusercontent.com/8700322/32731424-c0fdd6b6-c857-11e7-9a54-25b2d7c74ede.png)

**Comment by joshua-rutherford** [comment]
@spmcbride1201, we've begun using certificates issued by this CA in other projects: https://github.com/DecipherNow/certifiable.  The docker image is up on docker hub so you can just 
```
docker run -p 4567:4567 deciphernow/certifiable:latest
```
Then use postman or curl to generate and retrieve the certificates.
