### ISSUE TITLE
Unstyled settings button as page loads

### ISSUE THREAD

**Issue by kaitmore** [DecipherNow/gm-fabric-dashboard#957]
Settings cog button in upper right of the header appears unstyled while page is loading

![screen shot 2017-11-13 at 12 41 52 pm](https://user-images.githubusercontent.com/22768918/32740194-26aa3f0a-c870-11e7-8a32-60d16caeb6ee.png)

**Comment by spmcbride1201** [comment]
I think this is something that has to do with the WebPack build process running the sass precompiler. I don't think this would occur in our builds.

**Comment by karinakeen** [comment]
https://stackoverflow.com/questions/36453826/how-to-stop-fouc-when-using-css-loaded-by-webpack

**Comment by karinakeen** [comment]
blocked by #1045

**Comment by karinakeen** [comment]
Buttons FOUC issues are resolved by #1045!
