### ISSUE TITLE
Chart x-axis gets cut off in IE11

### ISSUE THREAD

**Issue by karinakeen** [DecipherNow/gm-fabric-dashboard#963]
![screen shot 2017-11-13 at 3 57 41 pm](https://user-images.githubusercontent.com/26534838/32749356-1ea4c65a-c88d-11e7-959a-e6925697a031.png)
![screen shot 2017-11-13 at 3 58 41 pm](https://user-images.githubusercontent.com/26534838/32749349-1c3962f4-c88d-11e7-965b-b60f4f829dd6.png)

**Comment by kaitmore** [comment]
This bug is also present in Routes and Functions as well

**Comment by karinakeen** [comment]
Instead of changing AppContent flex setting, change the direct parent container flex setting.  See #1152

**Comment by karinakeen** [comment]
This is fine.  Closing per #1152
