### ISSUE TITLE
Service cards are blurry on hover in Safari

### ISSUE THREAD

**Issue by jsweetland** [DecipherNow/gm-fabric-dashboard#990]
## Expected Behavior
Service cards enlarge slightly on mouse hover, appearing otherwise normal.

## Actual Behavior
Service cards enlarge slightly on mouse hover and appear blurred.

## Steps to Reproduce the Problem
1. Open the app at edge.deciphernow.com.
2. Hover over the card for a stable service.
3. Note that the contents of the card are blurry.

## Specifications
- Version: 0.9.1
- Platform: Safari 11.0.1 on macOS High Sierra 10.13.1

**Comment by tilleryd** [comment]
@jsweetland nice find, i didn't even notice that
