### ISSUE TITLE
Extra icons displayed in list view for not authorized services

### ISSUE THREAD

**Issue by karinakeen** [DecipherNow/gm-fabric-dashboard#991]
## Expected Behavior
Regular status icons for services

## Actual Behavior
'Not authorized services' such as Nachos and Grace Hopper Battleship Control Program display extra glyphs after status display

## Steps to Reproduce the Problem

  1. Fabric - List View - Group by Capability OR Group by Owner

## Specifications

  - Version: 0.9.1
  - Platform: Chrome 61
  - Subsystem:

<img width="1398" alt="screen shot 2017-11-15 at 1 29 22 pm" src="https://user-images.githubusercontent.com/26534838/32853495-768f2ebe-ca09-11e7-90cf-42d94447c9d5.png">

**Comment by spmcbride1201** [comment]
I think this one is working as intended. The Icons are indicating no metrics or not authorized. Can you confirm this looks right to you @shanberg?

**Comment by shanberg** [comment]
This is as I'd imagined it. It’s open to discussion on usability though, if you think the indicator should be something else, if the icons aren't clear enough, should be somewhere else, etc.

**Comment by karinakeen** [comment]
@shanberg 
Maybe the indicator should replace the status icons and be red color.  And the icon next to 'Grace Hopper Battleship' looks like Vital icon.  


![screen shot 2017-11-16 at 11 04 19 am](https://user-images.githubusercontent.com/26534838/32901539-0997cd10-cabe-11e7-8900-aaca2f101506.png)

![screen shot 2017-11-16 at 11 04 46 am](https://user-images.githubusercontent.com/26534838/32901534-071121a4-cabe-11e7-90a7-512724e1b8c1.png)

**Comment by spmcbride1201** [comment]
I think I'd prefer to keep it as is. The status icons and the other icons communicate different things, and I don't want us to feel like we need to get a single icon to represent all of these states.
