### ISSUE TITLE
Explorer View Chart Resizes on Hard Refresh

### ISSUE THREAD

**Issue by kaitmore** [DecipherNow/gm-fabric-dashboard#993]
## Expected Behavior
- Chart should fit page

## Actual Behavior
- Chart is about half the size 

## Steps to Reproduce the Problem

  1. Navigate to an instance dashboard and then to the Explorer tab
  2. Select an item
  3. Hard refresh

## Specifications

  - Version: 0.9.1
  - Platform: macOS Sierra 10.12.6
  - Subsystem: Confirmed bug in Chrome 61 & Safari 11

**Comment by spmcbride1201** [comment]
This feels related to the work that @7ruth and I were doing.

**Comment by spmcbride1201** [comment]
@kaitmore - I'm having trouble recreating this issue now. Do you see this still?

**Comment by kaitmore** [comment]
@spmcbride1201  Nope, it seems to be gone.
