### ISSUE TITLE
Fabric view: slight flicker of ErrorBoundary component on page load

### ISSUE THREAD

**Issue by tilleryd** [DecipherNow/gm-fabric-dashboard#994]
## Expected Behavior
Page loads only with elements that "should" be visible.

## Actual Behavior
Page loads with the ErrorBoundary component briefly present. 
<img width="1920" alt="screen shot 2017-11-15 at 1 59 45 pm" src="https://user-images.githubusercontent.com/2581080/32854653-4a932d7a-ca0d-11e7-8519-4aa7d454e951.png">

## Steps to Reproduce the Problem

  1. Refresh page
  1. Observe ErrorBoundary component briefly visible with no text in it

## Specifications

  - Version: 0.9.1
  - Platform: macOS Sierra 10.12.4
  - Subsystem: Safari 10.1

**Comment by karinakeen** [comment]
Unable to reproduce the problem in browserstack.  Confirming with others...

**Comment by karinakeen** [comment]
@tilleryd Unable to reproduce the problem in browserstack. I'd like to test again with slow load but Safari doesn't seem to have devtool network throttling option.

**Comment by karinakeen** [comment]
@spmcbride1201 I dont see this issue anymore.

**Comment by spmcbride1201** [comment]
@karinakeen - Okay go ahead an close!
