### ISSUE TITLE
Keyboard navigation isn't working properly in Safari

### ISSUE THREAD

**Issue by tilleryd** [DecipherNow/gm-fabric-dashboard#995]
## Expected Behavior
Tabbing through the page controls should highlight them.

## Actual Behavior
Only Search, Group and Sort controls are highlighted.

## Steps to Reproduce the Problem

  1. Open Safari 10.1
  1. Hit tab once and notice that the Skip Navigation control is not displayed
  1. Hit tab multiple times
  1. Observe that only Search, Group and Sort controls are highlighted

## Specifications

  - Version: 0.9.1
  - Platform: macOS Sierra 10.12.4
  - Subsystem: Safari 10.1

**Comment by tilleryd** [comment]
This issue may need to be broken out into smaller chunks per page.

**Comment by spmcbride1201** [comment]
@karinakeen, please convert this into an epic and decompose into multiple issues all assigned to you after you investigate what's going on.

**Comment by 7ruth** [comment]
@karinakeen, try this to see if this helps with this ticket.  
Follow these steps to turn on Full Keyboard Access:
Choose Apple menu > System Preferences, then click Keyboard.
Click Shortcuts.
To navigate only to text boxes and lists on the screen, select "Text boxes and lists only." To enable Full Keyboard Access and navigate to all controls on the screen, select "All controls."

**Comment by karinakeen** [comment]
To enable tabs in Safari, you have to enable tab access in both browser and mac setting.

Mac:  
Follow these steps to turn on Full Keyboard Access:
Choose Apple menu > System Preferences, then click Keyboard.
Click Shortcuts.
To navigate only to text boxes and lists on the screen, select "Text boxes and lists only." To enable Full Keyboard Access and navigate to all controls on the screen, select "All controls."

Safari
"Preferences > Advanced > Press tab to highlight each item on a page".

**Comment by karinakeen** [comment]
Safari 10.1 
Tab working on instance service view
<img width="1302" alt="screen shot 2017-12-05 at 10 16 48 am" src="https://user-images.githubusercontent.com/26534838/33614705-20c3148a-d9a6-11e7-859d-e0e21c7b68d9.png">

Tab working on fabric services view
<img width="918" alt="screen shot 2017-12-05 at 10 15 30 am" src="https://user-images.githubusercontent.com/26534838/33614723-2c72057a-d9a6-11e7-8ea2-f18e35d5976b.png">

**Comment by karinakeen** [comment]
@spmcbride1201 App headers, footer, instance view, service view, threads view, explorer setting are all selectable in Safari  10.1  after turning on the browser setting.  We should add the above instructions to the user guide.
