### ISSUE TITLE
ErrorBoundary component is pushed up too high in Safari

### ISSUE THREAD

**Issue by tilleryd** [DecipherNow/gm-fabric-dashboard#996]
## Expected Behavior
ErrorBoundary component is displayed vertically/horizontally centered in the page.

## Actual Behavior
ErrorBoundary component is displayed over the app header navigation.

![screen shot 2017-11-15 at 2 32 19 pm 2](https://user-images.githubusercontent.com/2581080/32856229-2cdeeb5c-ca12-11e7-8b4c-74069a9f041e.png)

## Steps to Reproduce the Problem

  1. Click on the Warning navigation control
  1. Observe the placement of the ErrorBoundary component

## Specifications

  - Version: 0.9.1
  - Platform: macOS Sierra 10.12.4
  - Subsystem: Safari 10.1

**Comment by spmcbride1201** [comment]
Look related to #994
